### ISSUE TITLE
Don't scale crosshair

### ISSUE THREAD

**Issue by fathutt** [shinyquagsire23/OpenJKDF2#105]
Crosshair now is scaled with resolution or display width. It's huge on ultrawide.
![image](https://user-images.githubusercontent.com/7819980/192131107-8ca19274-f97a-4a7f-bb50-5c59b3e2af71.png)

**Comment by shinyquagsire23** [comment]
Fixed (330542d176487cd7851a4e3029ccc844cb17f92c), will be included in next release

**Comment by shinyquagsire23** [comment]
Fixed v0.6.10
