### ISSUE TITLE
Parts of weapon models disappear at certain FOVs and aspects

### ISSUE THREAD

**Issue by StrikerMan780** [shinyquagsire23/OpenJKDF2#106]
Parts of weapon models end up disappearing or clipping oddly in widescreen, or with different FOVs. Like in this case where most of the scope of the E-11 has disappeared:
![image](https://shadowmavericks.com/files/ShareX/openjkdf2-64_2022-09-28_15-54-20.png)
Using 80 FOV with Hor+.

This issue gets especially egregious with JKE installed, where it is very noticeable with the thermal detonator, bowcaster (polygon order is messed up), and the concussion rifle.

**Comment by shinyquagsire23** [comment]
Fixed (7bd15157e8a9c508b46940fba43acdf420f2bc0f), set for next release

**Comment by shinyquagsire23** [comment]
Fixed v0.6.12
