### ISSUE TITLE
Skybox textures moving

### ISSUE THREAD

**Issue by winnie476** [shinyquagsire23/OpenJKDF2#107]
The skybox textures appear to shift while looking around as seen in the two videos below:

https://user-images.githubusercontent.com/114696413/193125205-19ce7cb1-f915-4660-ae05-69412cedfe15.mp4

https://user-images.githubusercontent.com/114696413/193125207-591d82b3-1861-44e0-b8a5-9f2d870f1a90.mp4

**Comment by shinyquagsire23** [comment]
I thiiiiink the original game does this but I need to double check. The JK skybox was always kinda weird but it's entirely possible that some of them aren't supposed to move.

**Comment by shinyquagsire23** [comment]
Yeah checked side by side with an unmodified JK.EXE and the behavior is identical. Always kinda confused me but eh, maybe I'll add a jkgfxmod extension to allow it to be more like a traditional skybox.
