### ISSUE TITLE
MOTS tutorial?

### ISSUE THREAD

**Issue by orderorder** [shinyquagsire23/OpenJKDF2#109]
i have seen the youtube video in which you run MOTS, but there is no tutorial about it. 

Thanks for this project

**Comment by shinyquagsire23** [comment]
So, MoTS support is very very very early at the moment, and the first release that has any MoTS additions is v0.6.9. But if you're interested in searching for bugs, launch `openjkdf2-64` with the `-motsCompat` argument. I'll probably add proper documentation when I have enough implemented that the game can be completed, ETA ~2-3 months?
