### ISSUE TITLE
SSAO rendering on lightsabers and possibly other weapons

### ISSUE THREAD

**Issue by Vortikai** [shinyquagsire23/OpenJKDF2#113]
SSAO is rendering on the emissive effects on lightsabers. It looks wonky in terms of the particle effects on the edge, e.g. the transparency showing through the white center of the saber against borders of objects such as table legs and boxes. Disabling SSAO makes it so the transparency isn't an issue, and the sabers have a solid white center.

I tried but was unable to confirm with other weapons, such as the Stormtrooper Rifle, which I suspect also has SSAO rendering on it. It's difficult to see, but I suspect this is the case with opaque first person mesh weapons.

It could be something to do with in game brightness which can't be modified, but that should be good when set to 0 which is the default for Openjkdf2, though I could be totally off the mark with this hypothesis.

The issue is seen in the screenshot for issue #95. Attached are a few additional photos of the issue. It's best to test it yourself since movement helps identify the discolorations.

![kuva](https://user-images.githubusercontent.com/63983128/195465580-495a6270-f4a9-48cb-8c4d-e59c8a00b3b6.png)
![kuva](https://user-images.githubusercontent.com/63983128/195465943-f556b33d-d563-48e7-bdbe-2816f89ae19c.png)

A video demostration
![video](https://user-images.githubusercontent.com/63983128/195568628-28dc8576-4262-4427-8bf4-b2f0a457685c.mp4)

And a comparison of SSAO on and off:
![openjkdf2-64_2022-10-13_10-37-34-25](https://user-images.githubusercontent.com/63983128/195558309-483cf2df-4a50-4a48-95bb-35d36c59a1d4.jpg)
![openjkdf2-64_2022-10-13_10-37-50-17](https://user-images.githubusercontent.com/63983128/195558325-8f467af8-b031-4da0-9b48-06feaf17b89b.jpg)

The following two screenshots illustrate another problem that could be a separate issue related to bloom, or a separate issue that is also affected by brightness. Regular JKGFXMod without OpenJKDF2 renders the color of the saber more smoothly than OpenJKDF2. Here's a screenshot of the green saber in JKGFXMod with EMJK

![kuva](https://steamuserimages-a.akamaihd.net/ugc/782979273619376014/7488EA6F740D9CD72571361A80C3FC44BADDADEE/?imw=5000&imh=5000&)
And another screenshot with the saber emissive textures in OpenJKDF2 that looks off due to the more solid coloring/edge/emissive lights of the saber, the less transparent green near the center white of the saber:
![unknown](https://user-images.githubusercontent.com/63983128/195568109-7b1a7112-5926-4212-bebc-93c6bac0693b.png)

Here's a more stark comparison. The first is JKGFXMod and EMJK which looks fantastic to me:
![1](https://user-images.githubusercontent.com/63983128/195687898-bd09b205-4666-479e-8aa0-6335cc69810e.jpg)
The second one is OpenJKDF2 and EMJK which is less desirable:
![20221014005752_1](https://user-images.githubusercontent.com/63983128/195719653-c35d780e-6150-46ca-84cd-e9aaba0109c5.jpg)
And third one below is OpenJKDF2, JKNUP, and JKNUP Annex which is what I have been using for emissive textures:
![2](https://user-images.githubusercontent.com/63983128/195687646-e6fe9717-f318-488b-a81c-22afa115a657.jpg)

Note that the lights on the wall and saber should be the same in all of these, hopefully using the first screenshot's with JKGFXMod and EMJK's style lights/colors/bloom/whatever else settings.

If you have any idea why the wall lights and the lightsaber is overly saturated, I appreciate any help you can give. This is my number one issue right now. Again, not sure if it's SSAO, bloom, color profiles, or what. It could be a bloom intensity issue or a color spacing one. Customization for bloom intensity could help mitigate it possibly. I thought I'd bring this to your attention as well, as I desperately want help for this one.

Windows 11
[v0.6.11 64-bit](https://github.com/shinyquagsire23/OpenJKDF2/releases/tag/v0.6.11)
I performed a clean install prior to testing this with only OpenJKDF2, JKNUP and emissive lightsaber textures in a jkgm materials folder--jkgfxmod is not installed. No shaders. All options in the right of the Display settings are enabled, e.g. bloom, texture filtering, HiDPI, etc. SSAA and Gamma are at default 1.0 values.

**Comment by shinyquagsire23** [comment]
The SSAO issue is definitely fixed in [v0.6.12](https://github.com/shinyquagsire23/OpenJKDF2/releases/tag/v0.6.12), it was mostly just on the backburner for a bit.

To expand on the bloom: OpenJKDF2 and jkgfxmod use different shaders, so everything is ~approximate, but bloom and SSAO are things I occasionally tweak. I actually hadn't realized how bad the green looked though because I have some debug cheats that always change my saber purple.

I ended up updating my bloom to not be quite as blown out, and I'm pretty happy with the results. They're not exactly the same as jkgfxmod, but the more I looked at jkgfxmod the more blown out/color banded it seemed to be.

**Old Bloom:**
![old](https://user-images.githubusercontent.com/1224096/195761871-4d48c318-03e5-4a00-bd42-63820cd66e5c.png)
**New Bloom:**
![new_bloom](https://user-images.githubusercontent.com/1224096/195761885-b6a64908-dfd0-4cdf-87e2-0f77db60fbba.png)

**Comment by Vortikai** [comment]
Much better implementation. It's difficult adjusting bloom values, so I suggest get to a point you're comfortable with them and possibly implement an advanced setting bloom adjustment slider down the line for this project for intensity or something.

The reason for this is one of the bigger material packs, JKNUP, doesn't appear to play nicely with the adjusted bloom values on my end after the update to the latest [v0.6.12](https://github.com/shinyquagsire23/OpenJKDF2/releases/tag/v0.6.12). Here's JKNUP and Annex in OpenJKDF2 with the latest version with your bloom tweaks:
![20221014134348_1](https://user-images.githubusercontent.com/63983128/195835310-9b3c0bf1-bcb6-4843-8c32-a00e3b0ad9bb.jpg)

The wall lights are muted compared to the previous one. Here is just OpenJKDF2, no material packs loaded, which is akin to your screenshot above:

![20221014134459_1](https://user-images.githubusercontent.com/63983128/195835362-34430e1f-32c1-4e9b-b81c-49b622f06bd2.jpg)

Our current solution is to find and replace all emissive factors in the json for the material pack (metadata), so find 1.7999999523162842 and replace it with 2.7999999523162842 or something seems to correct the issue. Later when you are happy with bloom tweaks in OpenJKDF2, hand-adjustments for each emissive factor could be done for material packs such as JKNUP.

As the SSAO issue is solved as per [v0.6.12](https://github.com/shinyquagsire23/OpenJKDF2/releases/tag/v0.6.12), you may close this issue when you see fit. I made a separate issue #115 that is a feature request for user-defined bloom adjustments.

**Comment by shinyquagsire23** [comment]
sweet, I'll go ahead and close it
