### ISSUE TITLE
Correction of pick-up item illumination in third person with sabers out

### ISSUE THREAD

**Issue by Vortikai** [shinyquagsire23/OpenJKDF2#117]
I personally don't care about this one, but thought I'd share anyway in case anyone is interested.

Pickups are illuminated in third person only with a lightsaber out, but not at all in first person. This is a vanilla JK issue, I believe.

First, first person with fist out, no illumination on pick-up items.
![20221014170411_1](https://user-images.githubusercontent.com/63983128/195900627-0bc76d60-df2f-46cc-880f-f7f6aa718f9c.jpg)
Second, first person with lightsaber out, no illumination on pick-up items.
![20221014170423_1](https://user-images.githubusercontent.com/63983128/195900703-53878ab7-d8dd-4d5e-8d15-0286bd27f57e.jpg)
Third, third person with a lightsaber out, illumination on pick-up items.
![20221014170427_1](https://user-images.githubusercontent.com/63983128/195900830-c86dba8c-3f23-45f9-be51-0d40db6d9f3c.jpg)
Fourth, third person with fists out, no illumination on pick-up items.
![20221014170431_1](https://user-images.githubusercontent.com/63983128/195901053-ad825955-08f4-47c2-b4a0-d672f4b3976b.jpg)

**Comment by Vortikai** [comment]
Happens with corpses too and the illumination of these in third person depends on positioning. 

Tested in Baron's Hed as there's ample bright daylight outside. From level start, follow the direction of the water in the canals to find pickups in light areas. Then, from level start, go the opposite direction as if you are advancing the level into the dark corridors that help you bypass the strong water flow with health pickups in a dark area.

**Comment by PalmliX** [comment]
I think this might also be occurring with walls that can get blown up. I noticed this especially in level 19 valley of the jedi, if you take the lightsaber out they stick out like a sore thumb.

**Comment by shinyquagsire23** [comment]
Fixed v0.7.5
