### ISSUE TITLE
Freeze on entering/exiting ESC menu from in-game too many times

### ISSUE THREAD

**Issue by OCircles** [shinyquagsire23/OpenJKDF2#12]
Windows 10, v0.1.2 64-bit Debug build from releases page. Found this when holding down ESC to test how fast going from game to menu and back was. After entering the ESC menu 14 times exactly the application will be unresponsive and be stuck at the menu until forcing exit.

Tested right upon starting without interacting with anything else on four different levels of The Force Awakens episode.

**Comment by shinyquagsire23** [comment]
Fixed in 54baaf7e3a2bfbd41ad7ce05ac7eccf8324e38fe
