### ISSUE TITLE
Security Camera in level 2 of MOTS is inescapable.

### ISSUE THREAD

**Issue by StrikerMan780** [shinyquagsire23/OpenJKDF2#121]
Once you use the security camera in the second level of MOTS (in the caves behind the starting point), you can't back out of it, leaving you permanently stuck viewing the cams.

**Comment by shinyquagsire23** [comment]
Ahhhh I was wondering if the rest of the input overrides were used, guess I'll have to see where they added those hooks at.

**Comment by shinyquagsire23** [comment]
Might be fixed with v0.6.14? I added the Activate `playeraction` COG hooks, as well as the force/inventory scroll + use inputs.

**Comment by StrikerMan780** [comment]
I'll check it out soon
