### ISSUE TITLE
Boss Level Crashes

### ISSUE THREAD

**Issue by darthbdaman** [shinyquagsire23/OpenJKDF2#123]
Whenever I enter episode 7 (or any lightsaber boss level according to my testing) the game crashes. I'm using the upscale texture pack and special effects annex (though this also seems to happens without them

Error occurred on Friday, October 21, 2022 at 11:32:54.

JediKnight.exe caused an Access Violation at location 00007FF61695CBDA in module JediKnight.exe Reading from location 000000000000134C.

AddrPC           Params
00007FF61695CBDA 000001FBE39272C8 00007FF616953CD4 000001FBF5387B70  JediKnight.exe!sithInventory_GetCurWeapon
00007FF616997B86 000001FBE39272C8 0021000100000006 00007FF6171AA800  JediKnight.exe!jkEpisode_UpdateExtra
00007FF6169DA591 000000003BDA740E 00007FF600000006 3F8000003F800000  JediKnight.exe!sithThing_TickAll
00007FF6169A7844 00000078663FF7C0 00007FF6169A1DF2 00007FF600000000  JediKnight.exe!sithMain_Tick
00007FF6169A08D5 0000000000000005 010001FB0000000A 0000000000000000  JediKnight.exe!jkMain_GameplayTick
00007FF61699FDD0 0000000000000000 00007FF60000000F 0000000000000000  JediKnight.exe!jkMain_GuiAdvance
00007FF6169C4365 0000000000000000 000000780000000F 0000000000000000  JediKnight.exe!Window_Main_Loop
00007FF6169C4656 0000000000000001 000001FB99FF7ED0 00000078663FFD80  JediKnight.exe!Window_Main_Linux
00007FF6169E9CA2 0000000000000001 000001FB99FF7ED0 000000000000003E  JediKnight.exe!SDL_main
00007FF616A054C6 0000000000000000 000000000000003F 00007FF61725FEA8  JediKnight.exe!main_getcmdline
00007FF6168E13AE 0000000000000000 0000000000000000 0000000000000000  JediKnight.exe!__tmainCRTStartup
00007FF6168E14C6 0000000000000000 0000000000000000 0000000000000000  JediKnight.exe!WinMainCRTStartup
00007FFF45A27034 0000000000000000 0000000000000000 0000000000000000  KERNEL32.DLL!BaseThreadInitThunk
00007FFF473426A1 0000000000000000 0000000000000000 0000000000000000  ntdll.dll!RtlUserThreadStart

JediKnight.exe
ntdll.dll   	6.2.19041.2130
KERNEL32.DLL	6.2.19041.1889
KERNELBASE.dll	6.2.19041.2130
apphelp.dll 	6.2.19041.2075
ADVAPI32.dll	6.2.19041.2130
msvcrt.dll  	7.0.19041.546
sechost.dll 	6.2.19041.1865
RPCRT4.dll  	6.2.19041.1806
GDI32.dll   	6.2.19041.2130
win32u.dll  	6.2.19041.2130
gdi32full.dll	6.2.19041.2130
msvcp_win.dll	6.2.19041.789
ucrtbase.dll	6.2.19041.789
USER32.dll  	6.2.19041.2130
IMM32.dll   	6.2.19041.546
ole32.dll   	6.2.19041.1202
combase.dll 	6.2.19041.2130
OLEAUT32.dll	6.2.19041.985
SETUPAPI.dll	6.2.19041.1741
cfgmgr32.dll	6.2.19041.1620
bcrypt.dll  	6.2.19041.1023
SHELL32.dll 	6.2.19041.2075
WS2_32.dll  	6.2.19041.546
OPENGL32.dll	6.2.19041.2075
VERSION.dll 	6.2.19041.546
glew32.dll  	2.1.0.0
WINMM.dll   	6.2.19041.546
OpenAL32.dll	1.21.1.0
GLU32.dll   	6.2.19041.2075
shcore.dll  	6.2.19041.1865
exchndl.dll 	0.9.3.0
PSAPI.DLL   	6.2.19041.546
mgwhelp.dll 	0.9.3.0
dbghelp.dll 	6.2.19041.867
dbgcore.DLL 	6.2.19041.789
uxtheme.dll 	6.2.19041.2130
RTSSHooks64.dll
SHLWAPI.dll 	6.2.19041.2075
IconCodecService.dll	6.2.19041.1
WindowsCodecs.dll	6.2.19041.1706
mscms.dll   	6.2.19041.746
USERENV.dll 	6.2.19041.572
ColorAdapterClient.dll	6.2.19041.546
icm32.dll   	6.2.19041.546
kernel.appcore.dll	6.2.19041.546
bcryptPrimitives.dll	6.2.19041.1415
clbcatq.dll 	2001.12.10941.16384
MMDevApi.dll	6.2.19041.1503
DEVOBJ.dll  	6.2.19041.1620
avrt.dll    	6.2.19041.546
hid.dll     	6.2.19041.546
WINTRUST.dll	6.2.19041.2075
CRYPT32.dll 	6.2.19041.1889
MSASN1.dll  	6.2.19041.546
dinput8.dll 	6.2.19041.1
inputhost.dll	6.2.19041.1741
wintypes.dll	6.2.19041.2130
PROPSYS.dll 	7.0.19041.1741
CoreMessaging.dll	6.2.19041.746
CoreUIComponents.dll	6.2.19041.546
ntmarta.dll 	6.2.19041.546
Windows.Gaming.Input.dll	6.2.19041.1566
twinapi.appcore.dll	6.2.19041.1865
MSCTF.dll   	6.2.19041.2075
AppXDeploymentClient.dll	6.2.19041.2075
nvoglv64.dll	31.0.15.1694
WTSAPI32.dll	6.2.19041.546
CRYPTBASE.DLL	6.2.19041.546
cryptnet.dll	6.2.19041.906
drvstore.dll	6.2.19041.1949
wldp.dll    	6.2.19041.2075
ffbroker.dll	6.2.19041.746
deviceaccess.dll	6.2.19041.1865
windows.storage.dll	6.2.19041.2130
dxcore.dll  	6.2.19041.546
nvspcap64.dll	3.25.1.27
profapi.dll 	6.2.19041.844
dwmapi.dll  	6.2.19041.746
powrprof.dll	6.2.19041.546
UMPDC.dll
WINSTA.dll  	6.2.19041.2075
textinputframework.dll	6.2.19041.2075
libGameNetworkingSockets.dll
IPHLPAPI.DLL	6.2.19041.1865
libgcc_s_seh-1.dll
libwinpthread-1.dll	1.0.0.0
libstdc++-6.dll
libprotobuf.dll
AUDIOSES.DLL	6.2.19041.1865
resourcepolicyclient.dll	6.2.19041.546

Windows 6.2.9200
DrMingw 0.9.3

**Comment by shinyquagsire23** [comment]
Should be fixed in v0.6.15? I added some nullptr checks there

**Comment by darthbdaman** [comment]
Verifying v0.6.15 fixes the problem. Thank you
