### ISSUE TITLE
MOTS crashes at Level 2 Secret area (stdDisplay)

### ISSUE THREAD

**Issue by Alex3474247** [shinyquagsire23/OpenJKDF2#127]
An unhandled exception occurs in OpenJKDF2 in Level 2, MOTS mode, on Windows 64bit.
This secret area, on the last screenshot:
![MOTS level2 unhandled exception in MSVC debugger1](https://user-images.githubusercontent.com/17110303/200132585-e1820295-9f52-4eab-a4ef-29a3e8c896b6.png)
![MOTS level2 exception in MSVC debugger1](https://user-images.githubusercontent.com/17110303/200132590-d731b98c-3172-47c3-a6ca-37b26f120fea.png)
![MOTS level2 exception _error_1](https://user-images.githubusercontent.com/17110303/200132335-7ef90836-ba67-473a-a3a9-fe5646afe5bc.png)

**Comment by Alex3474247** [comment]
I have tried it on the latest version (0.7.5), it's OK, no crash or this crash is floating, does not always occur.

**Comment by Alex3474247** [comment]
Further information - in items.dat I have edited the max battery (bin id = 13) carrying capacity to a higher value, that is more than 225, for example 300. When I pick up the battery (sithInventory.c, line 504, binIdx=13), (I already had 225 points) I got another 25.0 battery points, pow_battery_m.cog and this crash occurs immediately. I think that the problem is related to this carrying capacity, but it is strange because the battery charge is not displayed in the game initially.

**Comment by shinyquagsire23** [comment]
I thiiiiink this might be fixed now with the HUD changes, I specifically made sure to right-align the text (for HUD upscales but also for numbers >99)

**Comment by Alex3474247** [comment]
I'm gonna test it anyways today or this week. I'm gonna repeat my old HUD
changes on this latest commit (health, shields, ammo values up to 9999).
Now health displays only up to 100, shields up to 200, i'm gonna change
this in my copy of the source.

ср, 25 янв. 2023 г., 11:50 Max Thomas ***@***.***>:

**Comment by Alex3474247** [comment]
I confirm that the problem has been solved.
