### ISSUE TITLE
Sounds restarting on exiting from ESC menu to in-game

### ISSUE THREAD

**Issue by OCircles** [shinyquagsire23/OpenJKDF2#13]
Windows 10, v0.1.2 64-bit Debug build from releases page. Try going in and out of ESC menu at the start of Escape with the Map to hear Kyle sing "Jan-- Jan-- Jan-- Jan-- Jan-- Jan-- "

**Comment by shinyquagsire23** [comment]
Fixed 1d79cd922a083e5e5b0c75093139a1a615382e10
