### ISSUE TITLE
Game crash when starting lv 7/Yun boss fight

### ISSUE THREAD

**Issue by Ivaren** [shinyquagsire23/OpenJKDF2#131]
Playing the steam version with JKDF2 installed. Game crashes after cutscene before the fight with Yun. Attempted to launch game in -devmode from steam, then play the level through debug, still crashes. Debug plays all prior levels as well as the level after (level 8) perfectly fine. Also attempted having skip cutscenes on. Still crashes.

**Comment by shinyquagsire23** [comment]
Hmmm, I can't seem to recreate. Do you have an `OpenJKDF2.RPT` file in your resource folder that I can look at?
