### ISSUE TITLE
[Enhancement] Add pause to mission start screen

### ISSUE THREAD

**Issue by katastic** [shinyquagsire23/OpenJKDF2#135]
The missions load so blazingly fast on modern PCs, you don't have any time to read the mission text which, as I've found out, is pretty important--having no idea what's going on in the story until I alt-tab and google it.

All it needs is a text prompt that's says "ready, press any key" and a while loop that waits for any key press (or specifically space/enter/whatever).

**Comment by shinyquagsire23** [comment]
Added 962a687ecad6b57a2618d214fc5e442672adc35d, will be included in next release

**Comment by shinyquagsire23** [comment]
Added [v0.6.16](https://github.com/shinyquagsire23/OpenJKDF2/releases/tag/v0.6.16)
