### ISSUE TITLE
Mouse buttons cannot map to "move forward" and "move backward"

### ISSUE THREAD

**Issue by JBurkeKF** [shinyquagsire23/OpenJKDF2#136]
As of release v0.6.15 64-bit Debug, I can't remap the mouse buttons to the "move forward" or "move backward" actions.
![OpenJDKDF2MouseRemap](https://user-images.githubusercontent.com/17777807/209236466-681cfe9e-dc21-4f7e-9a2e-e25ced3e9c87.png)

In the Steam version (as well as the original game), I can map these actions.
![JediKnightSteamMouseRemap](https://user-images.githubusercontent.com/17777807/209236449-54598e24-0305-42eb-878e-79ebd62357be.png)

I don't think this is a high priority issue, but it would be nice to have.  Jedi Knight was the first game I played with mouse look, back before I knew the WASD key mapping existed, and I always used mouse 1 and mouse 2 for forward/back.  Thanks!

**Comment by JBurkeKF** [comment]
Closing as duplicate.

**Comment by shinyquagsire23** [comment]
Fixed v0.7.5
