### ISSUE TITLE
MoTS Turrets can move and fly

### ISSUE THREAD

**Issue by shinyquagsire23** [shinyquagsire23/OpenJKDF2#140]
Jumping and moving in the turrets causes them to fly around lol. Exiting leaves the object attached to the player for some reason, until saving and reloading?

**Comment by DanKorell** [comment]
I just found out about this from level 2 on MotS. I was able to get into the turret after picking up the ammo for it that was positioned next to it, but I couldn't work out how to exit it. At one point I pressed jump and the turret took off and I could move around, but I couldn't get back down to the ground. Had no option but to reload and not use the turret. So how are you meant to exit the turret? Is it spacebar (use) again?

**Comment by shinyquagsire23** [comment]
@DanKorell switching weapons will do it, it's very strange lol. The odd thing is that I definitely hooked the COG input override stuff correctly because the E-11 scope uses jump+crouch for zooming

**Comment by shinyquagsire23** [comment]
Fixed v0.7.10
