### ISSUE TITLE
MOTS camera + controller

### ISSUE THREAD

**Issue by PatrykIBM** [shinyquagsire23/OpenJKDF2#144]
Altough while playing with controller it seem like inputs are registered with bit of delay like player is actualy taking time to strafe right or left with full speed, the biggest problem is that it puts camera in very weird position like 100% zoomed rifle scope or someting. Mybe its connected with AFK problem with controller I reported for DF2. Moving mouse fixes camera. Weird.

**Comment by shinyquagsire23** [comment]
This might be fixed in v0.7.2?

**Comment by PatrykIBM** [comment]
Yes, I confirm with 1h of testing that's fixed. Thanks a lot! @shinyquagsire23
