### ISSUE TITLE
Cutscenes not working in MotS

### ISSUE THREAD

**Issue by Agorath** [shinyquagsire23/OpenJKDF2#148]
Hi,

I hope I'm not missing anything, searched through the readme, the open issues as well as the release notes, but didn't find anything regarding the MotS cutscenes.
I tried out MotS with the latest release, v0.7.0, and was able to play the first level with no problem, but noticed that the intro cutscene, the one with the scrolling text, etc., as well as the cutscene in between levels 1 and 2, didn't play.
Is that a known unimplemented feature, a bug, or am I missing something? :-)

Cheers,
Agorath

PS: Awesome work with OpenJKDF2, was finally able to play the base game from start to finish with no problem after many, many years! ❤️

**Comment by shinyquagsire23** [comment]
Yeah I'm working on cutscenes, MoTS used a new/different codec than DF2 so I'm having to implement that myself

**Comment by shinyquagsire23** [comment]
Implemented v0.7.1
