### ISSUE TITLE
Wandering Storm Troopers (MOTS)

### ISSUE THREAD

**Issue by orderorder** [shinyquagsire23/OpenJKDF2#149]
At the beginning of the first level in MOTS, there are several stormtroopers shooting at us. If we leave the base through the front door, we can see two stormtroopers wandering near the cliff, they don't shoot at us, sometimes they aim at us but don't shoot at us or just ignore us.

**Comment by Journeyman716** [comment]
This is an issue with vanilla as well, sometimes a Stormtrooper or two happens to walk towards the cliff, then turn around and start behaving like normal.

**Comment by orderorder** [comment]
in this case they dont seem to adopt a normal behaviour.

**Comment by Vortikai** [comment]
AI issues should be fixed at least as of v0.7.10 if not before. The two wandering off and not recognizing the player is typical in vanilla, but has been occurring less with me since the latest update personally. You might want to try testing the latest version as well

**Comment by orderorder** [comment]
Acabo de probar la versión 0.7.11. El comportamiento de los stormtroopers ha sido mejorado

**Comment by shinyquagsire23** [comment]
gonna go ahead and close this because I haven't been able to find any new AI discrepancies for a hot moment
