### ISSUE TITLE
TODOA - Various softlocks in Levels Suffocation and Drowning

### ISSUE THREAD

**Issue by Journeyman716** [shinyquagsire23/OpenJKDF2#153]
Suffocation:
- Destructible door that can't be broken by any weapons in OpenJK, but can in Vanilla. Required to activate a switch that raises an elevator from under a long gap (First Pic). This can be bypassed though if the player times their sprint-jump correctly.
- Section right after the previous part, after destroying a blast door, you need to kill every Clone/turret to initiate a cutscene that disables forcefields, but the cutscene never plays (Second Pic).

Drowning:
- One of the Rocket Clones in this Lab area is meant to drop a keycard for further progression, but the Keycard never drops (Third pic).
![vlcsnap-2022-12-29-20h25m36s732](https://user-images.githubusercontent.com/19245505/210028330-cc4c866b-4597-424b-8d66-1849643f3e27.png)
![vlcsnap-2022-12-29-20h25m41s618](https://user-images.githubusercontent.com/19245505/210028339-77026a88-2320-43e0-aa14-d6a298624e49.png)
![vlcsnap-2022-12-29-20h25m45s655](https://user-images.githubusercontent.com/19245505/210028344-cce303b7-40e4-4446-b6e4-d23eec97c7b7.png)

**Comment by shinyquagsire23** [comment]
Suffocation softlocks definitely fixed v0.7.6, haven't checked Drowning

**Comment by Journeyman716** [comment]
All of these softlock issues are fixed with 0.7.6.
