### ISSUE TITLE
Two types of Controller weirdness

### ISSUE THREAD

**Issue by DocLathropBrown** [shinyquagsire23/OpenJKDF2#159]
For whatever reason, my use of a controller operates the game, but I guess whatever built-in programming LucasArts had ignores OpenJKDF2's controller recognition and it keeps eventually doing the 3rd-person camera pan around Kyle Katarn, and the only way I can get it to stop is to bump the mouse or hit a key on the keyboard. I'm using a Dualshock 4 spoofing a 360 controller via DS4Windows.

The other option is to use a Dinput controller, but having one plugged in (a generic USB Gamecube clone) crashes OpenJKDF2 on startup.

I hope these can be addressed--I'd really like to play the game, as I never have before... but I'm not a keyboard/mouse kinda guy.

**Comment by shinyquagsire23** [comment]
The idle issue is fixed v0.7.2, for the crashing issue do you have an OpenJKDF2.RPT file?

**Comment by DocLathropBrown** [comment]
Yeah, I have the RPT file.

I actually had just downloaded 0.7.2 today in the hopes that it would have fixed the idle issue, but it did not, though it seemed as if it didn't happen DURING controller use this time. Once I stopped using the controller and let Kyle sit (to let the idle camera activate), using the controller didn't turn it back off, sadly.

**Comment by shinyquagsire23** [comment]
try redownloading just in case, I pushed a hotfix bc I realized I hadn't fixed it properly, so you might have grabbed the release before I reuploaded

And with the RPT file, if you could paste the entire thing (or the top 50 or so lines of the latest crash) that'd be great

**Comment by DocLathropBrown** [comment]
Here's the first entry from the RPT file:

Error occurred on Sunday, January 1, 2023 at 12:09:19.

openjkdf2-64.exe caused an Access Violation at location 0000000010003654 in module EZFRD64.DLL Reading from location 00000000178A0090.

AddrPC           Params
0000000010003654 00000000178A0080 0000000000000000 0000000000000000  EZFRD64.DLL!DllCanUnloadNow
0000000010001B2A 0000000000000010 0000000000000000 00007FFF178A0080  EZFRD64.DLL!DllCanUnloadNow
00007FFF3B6221FB 0000000000000000 0000000000000000 0000000000000000  WINMM.dll!PlaySoundW
00007FFF4A5626BD 0000000000000000 0000000000000000 0000000000000000  KERNEL32.DLL!BaseThreadInitThunk
00007FFF4ACEDFB8 0000000000000000 0000000000000000 0000000000000000  ntdll.dll!RtlUserThreadStart

openjkdf2-64.exe
ntdll.dll   	6.2.22621.900
KERNEL32.DLL	6.2.22621.963
KERNELBASE.dll	6.2.22621.963
ADVAPI32.dll	6.2.22621.608
msvcrt.dll  	7.0.22621.608
sechost.dll 	6.2.22621.608
RPCRT4.dll  	6.2.22621.1
GDI32.dll   	6.2.22621.608
win32u.dll  	6.2.22621.963
gdi32full.dll	6.2.22621.963
msvcp_win.dll	6.2.22621.608
ucrtbase.dll	6.2.22621.608
USER32.dll  	6.2.22621.900
IMM32.dll   	6.2.22621.755
ole32.dll   	6.2.22621.608
combase.dll 	6.2.22621.900
OLEAUT32.dll	6.2.22621.608
SETUPAPI.dll	6.2.22621.755
SHELL32.dll 	6.2.22621.900
WS2_32.dll  	6.2.22621.1
VERSION.dll 	6.2.22621.1
OPENGL32.dll	6.2.22621.608
GLU32.dll   	6.2.22621.608
dxcore.dll  	6.2.22621.608
WINMM.dll   	6.2.22621.608
glew32.dll  	2.1.0.0
OpenAL32.dll	1.21.1.0
cfgmgr32.DLL	6.2.22621.755
shcore.dll  	6.2.22621.900
exchndl.dll 	0.9.3.0
PSAPI.DLL   	6.2.22621.1
mgwhelp.dll 	0.9.3.0
dbghelp.dll 	6.2.22621.1
dbgcore.DLL 	6.2.22621.1
uxtheme.dll 	6.2.22621.608
RTSSHooks64.dll
SHLWAPI.dll 	6.2.22621.608
IconCodecService.dll	6.2.22621.1
WindowsCodecs.dll	6.2.22621.608
mscms.dll   	6.2.22621.608
icm32.dll   	6.2.22621.608
kernel.appcore.dll	6.2.22621.1
bcryptPrimitives.dll	6.2.22621.1
clbcatq.dll 	2001.12.10941.16384
MMDevApi.dll	6.2.22621.608
DEVOBJ.dll  	6.2.22621.755
avrt.dll    	6.2.22621.608
hid.dll     	6.2.22621.1
WINTRUST.dll	6.2.22621.900
CRYPT32.dll 	6.2.22621.674
MSASN1.dll  	6.2.22621.819
dinput8.dll 	6.2.22621.1
inputhost.dll	6.2.22621.608
CoreMessaging.dll	6.2.22621.608
CRYPTBASE.DLL	6.2.22621.1
Windows.Gaming.Input.dll	6.2.22621.1
bcrypt.dll  	6.2.22621.1
twinapi.appcore.dll	6.2.22621.755
WinTypes.dll	6.2.22621.900
MSCTF.dll   	6.2.22621.755
AppXDeploymentClient.dll	6.2.22621.900
Windows.System.UserDeviceAssociation.dll	6.2.22621.1
usermgrproxy.dll	6.2.22621.1
Windows.ApplicationModel.dll	6.2.22621.1
windows.storage.dll	6.2.22621.900
propsys.dll 	7.0.22621.608
profapi.dll 	6.2.22621.1
mssprxy.dll 	7.0.22621.900
directxdatabasehelper.dll	6.2.22621.963
nvoglv64.dll	31.0.15.2661
WTSAPI32.dll	6.2.22621.1
cryptnet.dll	6.2.22621.1
drvstore.dll	6.2.22621.1
wldp.dll    	6.2.22621.900
ntmarta.dll 	6.2.22621.1
dwmapi.dll  	6.2.22621.608
powrprof.dll	6.2.22621.900
UMPDC.dll   	6.2.22621.1
WINSTA.dll  	6.2.22621.608
textinputframework.dll	6.2.22621.900
CoreUIComponents.dll	6.2.22621.608
libGameNetworkingSockets.dll
IPHLPAPI.DLL	6.2.22621.1
libgcc_s_seh-1.dll
libwinpthread-1.dll	1.0.0.0
libprotobuf.dll
libstdc++-6.dll
AUDIOSES.DLL	6.2.22621.900
resourcepolicyclient.dll	6.2.22621.1
EZFRD64.DLL
DINPUT.dll  	6.2.22621.1

Windows 6.2.9200
DrMingw 0.9.3

**Comment by DocLathropBrown** [comment]
Update: Yeah, that was what happened. The hot fixed version seems to remove the idle camera, so my issues are fixed!

I only tried the Dinput controller I had in a hope to get around the issue to begin with, so while I'm sure you want to plug that Dinput crash issue, I'll be using my Xinput pad as I wanted to anyway!

**Comment by shinyquagsire23** [comment]
Ah, apparently EZFRD64.dll has a known issue where it doesn't work with 64-bit binaries (https://github.com/ppy/osu/issues/13634, https://forums.dolphin-emu.org/Thread-dolphin-dev-builds-past-5-0-3977-crash-on-startup-with-my-controller-plugged-in?page=2).

Frankly uh, whoever wrote the driver needs to fix their stuff lol. I think SDL2 is supposed to have some USB drivers included now specifically to mitigate some of these things? Dunno.

**Comment by Squall-Leonhart** [comment]
> Frankly uh, whoever wrote the driver needs to fix their stuff lol. I think SDL2 is supposed to have some USB drivers included now specifically to mitigate some of these things? Dunno.

They did, but the fixed library is hard coded for a specific adapter PID/VID.
