### ISSUE TITLE
Slowmo cheat has no effect

### ISSUE THREAD

**Issue by linusrachlis** [shinyquagsire23/OpenJKDF2#161]
For some reason the `slowmo 1` cheat doesn't work on either system I was able to test (Windows 10 or MacOS 12.6). Specifically, the result is that the game confirms "Slowmo is ON," but then the game still runs at normal speed.

It was one of my fav cheats, because I love how it turns action tactics more into strategy. The game can be punishing on hard, but going slowmo is a way to make the challenge more manageable in a way that's interesting rather than cheap and boring. It's like force speed, but for thought 🙂 

I have limited experience with game programming or systems programming, so investigating was a fun exercise, but I eventually ran into a wall. Basically, I found that typing `slowmo 1` sets a debug flag bit, but I couldn't find any code that is checking for that particular bit in the debug flags value. So I guess it makes sense that it doesn't work, but I don't know why nothing is checking for it. Maybe that code hasn't been decompiled yet, so I can't search for it? Or maybe the code that used to check for it was platform code and some of that was replaced with SDL to make it work on modern systems?

At any rate, I found a way to make it work that may well be a bad idea ([see branch](https://github.com/shinyquagsire23/OpenJKDF2/compare/master...linusrachlis:OpenJKDF2:slowmo)), although I've successfully played the game with it for a few hours on Win10 (only debug build from within Visual Studio -- to be honest, I couldn't figure out how to do a release build ...). I didn't think it was worth a PR, and looking at the other issues, I doubt this one will be a priority anyway. I share it (1) as a bad idea to stimulate others, when/if you do want to work on this, and (2) as a way for others to scratch their itch if they also miss slowmo 🙂 

Note: at first I thought the above timing-related change was somehow causing the X mouselook to become jerky, but it turned out that was just because VSync was off for the dev copy of the game. On my Win10 machine, X mouselook seems to be jerky when VSync is off for some reason, but that looks to be a separate issue.

I was originally much less concise about my investigation, so I'll leave that below. Just want to say thank you for the hard work on this project. Playing this game again, and now getting to hack on it too, has been tons of fun!

---

I saw that the `slowmo` command is created by `jkDev_RegisterCmd` here:
https://github.com/shinyquagsire23/OpenJKDF2/blob/9f7dc1e5b0cf2152004a13e8c6c3da10f0be333f/src/Main/jkDev.c#L57

The handler for the slowmo command is `jkDev_CmdDebugFlags3`. (For some reason, there is also `jkDev_CmdDebugFlags2` and `jkDev_CmdDebugFlags` which look identical to me.) These functions are used to handle various other commands, such as `whiteflag` (disable AI) and `jediwannabe` (god mode), depending on what `extra` arg is passed (7 for slowmo).

`sithCommand_CheatSetDebugFlags` seems to be what does the real work setting the debug flags:
https://github.com/shinyquagsire23/OpenJKDF2/blob/d6147d329223cdb24087f27c1904bdfd1f6df3f5/src/Main/sithCommand.c#L80

There is a switch based on that "extra" value. Depending on the value, a different bit will be flipped on or off in a global var, `g_debugmodeFlags`, unless the extra value was 1, in which case the target for bit flipping will be `sithRender_flag`, or 5, in which case the target will be the player actor's flags (which makes sense for god mode).

(This switch statement has a weird way of reusing the logic to set the flags by jumping to a label within the `5` case. Maybe this is sort of an artifact of the decompilation process, like the logic was inlined though it was maybe was a function in the original source? Decompilation is mostly a mystery to me currently.)

Anyway, under `case 7u` for slowmo, I see it's setting the 0x400 bit to the flags value:
https://github.com/shinyquagsire23/OpenJKDF2/blob/d6147d329223cdb24087f27c1904bdfd1f6df3f5/src/Main/sithCommand.c#L151-L154

However, I don't see this value being checked for anywhere.

Just to check my method, I looked for other checks of the flags. The AI code is littered with `if (g_debugmodeFlags & 1)` checks ([example](https://github.com/shinyquagsire23/OpenJKDF2/blob/e80708d691a1f4afc4abdb3236a5c591b334cca2/src/Cog/sithCogFunctionAI.c#L47)), which makes sense since the flags value's lowest bit is used for the "disable AI" mode:
https://github.com/shinyquagsire23/OpenJKDF2/blob/d6147d329223cdb24087f27c1904bdfd1f6df3f5/src/Main/sithCommand.c#L94-L97
("extra" value = 0 for that command)
https://github.com/shinyquagsire23/OpenJKDF2/blob/9f7dc1e5b0cf2152004a13e8c6c3da10f0be333f/src/Main/jkDev.c#L52

So, it seems like I should also be able to find `g_debugmodeFlags & 0x400` or the equivalent, `g_debugmodeFlags & 1024` somewhere. Even searching for all usage of `g_debugmodeFlags`, I don't see anything that might be checking for the 0x400 bit and none of it looks like the deep physics/gameplay/timing code I would expect to be involved with this flag.

I don't know if this means the flag is just being ignored (so, makes sense slowmo doesn't work), or it is being checked somewhere, but the code checking for it has not been decompiled yet -- in which case maybe the reason it doesn't work is more subtle.

From looking at the readme, it seems like most of the as-yet-not-decomped code is the rasterizer, and assuming I understand correctly what that is, it's not a system I'd expect to care about slowmo mode.

**Comment by shinyquagsire23** [comment]
Seems I accidentally removed the flag when I cleaned up `sithTime_Tick`, should be fixed when I push the next release

**Comment by shinyquagsire23** [comment]
Fixed v0.7.5
