### ISSUE TITLE
MotS Level 5 Force Boost Can't Be Picked Up

### ISSUE THREAD

**Issue by DanKorell** [shinyquagsire23/OpenJKDF2#163]
There is a Force Boost pickup in the third secret of MotS Level 5, as shown in the screenshot, but I can't pick it up at all. I even tried using Force Seeing to try to use up some Force energy but I still can't pick it up.

![image](https://user-images.githubusercontent.com/31672833/210456909-47665e9c-2c72-4209-b099-03c1cc1bd3da.png)

You can see it picked up here in a YouTube video from 4 years ago:
https://youtu.be/24cbWf1c2wA?t=623

**Comment by shinyquagsire23** [comment]
Ah, I think this is fixed now in v0.7.5, tested through lv5 and was able to pickup fine. The pickup script used the COG verb `PlaySoundLocal`, which I hadn't implemented, and implementing it had caused a slew of other issues due to savefile off-by-one bugs.
