### ISSUE TITLE
Modern HUD replacement doesn't work

### ISSUE THREAD

**Issue by Journeyman716** [shinyquagsire23/OpenJKDF2#165]
Using the modern HUD with OpenJK results in a heavily glitched default HUD instead of appearing as intended. Top is vanilla, bottom is OpenJK. Apparently caused by how OpenJK handles HUD scaling and textures.
![image](https://user-images.githubusercontent.com/19245505/210482999-b0bdcc9c-8901-4acf-a48f-cf10dd6e2cee.png)
![vlcsnap-2023-01-03-22h07m22s062](https://user-images.githubusercontent.com/19245505/210483006-685e8a50-940d-4908-8cbb-5f2591589f4c.png)

**Comment by shinyquagsire23** [comment]
Fixed v0.8.3
