### ISSUE TITLE
Lightsaber blade appears instantly when re-equipping saber in DF2 Level 4

### ISSUE THREAD

**Issue by Journeyman716** [shinyquagsire23/OpenJKDF2#167]
When attaining the Lightsaber in Level 4, the blade instantly appears if you swap to another weapon, then back to the saber. Even persists in savegames.

https://user-images.githubusercontent.com/19245505/210654076-196ff4c9-6cc9-434b-ba48-1750bc66ea8f.mp4

**Comment by shinyquagsire23** [comment]
Fixed v0.7.6
