### ISSUE TITLE
Changing from Fullscreen to Windowed (or vice versa) breaks the renderer (0.7.7)

### ISSUE THREAD

**Issue by DanKorell** [shinyquagsire23/OpenJKDF2#173]
When changing from fullscreen to windowed, the game just goes black, with the crosshair still showing. I found this out when I wanted to grab some screenshots of the Force Powers Allocation Screen bug, as I have to go into windowed mode to take screenshots. I also noticed that, having restarted in windowed to get my screenshot of the other bug, that going to fullscreen afterwards also broke it. The loading menu colours also get messed up - they showed various shades of red before loading to a black screen.

**Comment by shinyquagsire23** [comment]
Fixed v0.7.8
