### ISSUE TITLE
[MotS] The Blaster Cannon!

### ISSUE THREAD

**Issue by Vortikai** [shinyquagsire23/OpenJKDF2#174]
The blaster cannon on level 9 - The New Republic Escort Ship is indeed accessible, but once the character attempts to exit (I used spacebar), the character is projected forwards in the chair. Nothing in debug menu. The character is stuck with the cannon, unable to exit.

![kuva](https://user-images.githubusercontent.com/63983128/211673744-f031bca2-a8d1-472e-a79a-1aff68afb924.png)

**Comment by Vortikai** [comment]
This is a duplicate of #140 I just realized. I will leave this open in case you didn't know it happens in this particular level as well.

**Comment by shinyquagsire23** [comment]
I was never able to recreate the projectile launch thing, but I did just fix the weird scooting issue so maybe that will also fix some other things?

**Comment by Vortikai** [comment]
The blaster cannon works normally now as of [v0.7.10](https://github.com/shinyquagsire23/OpenJKDF2/releases/tag/v0.7.10) as it did in vanilla MOTS. The only issue remaining is #177 where SSAO is rendered over it.
