### ISSUE TITLE
Kyle animation corruption on loading save

### ISSUE THREAD

**Issue by OCircles** [shinyquagsire23/OpenJKDF2#18]
[Limbs warping time and space on load](https://streamable.com/049h6v)

[Animations getting corrupted after loading saves](https://streamable.com/psvbhc)

Doesn't happen all the time and corruptions vary wildly. Also seems to sometimes fix itself over time..?

[This one I thought was pretty funny](https://streamable.com/3qvhe9)

Might be related to Kyle's random spazzing as you run around

**Comment by shinyquagsire23** [comment]
Fixed v0.1.17, I'm not particularly happy with the fix because I still don't know why the issue was happening. Apparently the savefiles produced by OpenJKDF2 will reproduce the buggy behavior even on vanilla JK.EXE.
