### ISSUE TITLE
[MotS] actor_rc.cog failed attempts to call 'aisetmovetarget'

### ISSUE THREAD

**Issue by Vortikai** [shinyquagsire23/OpenJKDF2#181]
Probably nothing since things are working alright from my perspective, but the debugger shows a call to an ai piece that does not exist.

![kuva](https://user-images.githubusercontent.com/63983128/211877909-bb241810-d94d-436b-ae2a-339bc598adf0.png)

This is level 1 when Stormtroopers and Rebels are fighting in the second room, the one with the wall that explodes early in the level.

**Comment by shinyquagsire23** [comment]
Yeah I checked when I implemented the print and that verb just Doesn't Exist, the print is mostly there for mods/just in case
