### ISSUE TITLE
Mysteries of the Sith Level 10 - Door to space causes shaking

### ISSUE THREAD

**Issue by DanKorell** [shinyquagsire23/OpenJKDF2#187]
Is this a bug or is it how it is meant to be? There is a door to space in Level 10 of Mysteries of the Sith that when opened causes the screen to shake a few times. Not a constant shake, but like a shake, then say half a second later another, and again, until the door automatically closes.

Here's a screenshot of the door with the map overlaid to help identify it. It is at the point where you use the yellow droid wrench on the floor panels.

![image](https://user-images.githubusercontent.com/31672833/212211771-e322e929-b766-493a-8be7-dfae3d035da6.png)

**Comment by Vortikai** [comment]
This is in vanilla, meant to show players that it's bad to open doors to space.

**Comment by DanKorell** [comment]
If this is in vanilla then that's fine. But it does still seem odd. I mean, there's a forcefield in place otherwise you'd be blown out into space, and other openings to space (like the hangar bay doors in Level 9) don't cause any shaking (they have forcefields too). And if the door was dangerous to open when in space, you'd expect the ship's computer to lock it so that it won't open. The shaking isn't constant, either. So all in all, it just seems like a very strange design decision if it is indeed intended.
