### ISSUE TITLE
Using jkgfxmod on Linux 

### ISSUE THREAD

**Issue by Calinou** [shinyquagsire23/OpenJKDF2#188]
Is it possible to use jkgfxmod on Linux natively? I don't see any instructions in the README (nor on [jkgfxmod](https://www.moddb.com/mods/jkgfxmod)'s page, which seem specific to Windows).

**Comment by Vortikai** [comment]
JKGFXMod works fine on Linux, as well as OpenJKDF2. I am not sure what you're asking as there are no special instructions--just drop the contents of either mod into the JKDF2 or MOTS directory. With JKGFXMod there's additional configuration instructions found on the readme but it pertains to Linux as well.

**Comment by Calinou** [comment]
> JKGFXMod works fine on Linux, as well as OpenJKDF2. I am not sure what you're asking as there are no special instructions--just drop the contents of either mod into the JKDF2 or MOTS directory. With JKGFXMod there's additional configuration instructions required to set it up found on the readme but it pertains to Linux as well.

I can confirm this works, thanks :slightly_smiling_face:

**Comment by Vortikai** [comment]
Note that OpenJKDF2 integrates JKGFXMOD natively. It does not require configuration, additional files, or JKGFXMOD to be installed at the same time. Shiny also doesn't really do anything with JKGFXMOD other than integrate it. If you're looking specifically for JKGFXMOD stuff, https://github.com/jdmclark/jkgfxmod is your page.
