### ISSUE TITLE
Savegames sometimes play the wrong music upon loading

### ISSUE THREAD

**Issue by Journeyman716** [shinyquagsire23/OpenJKDF2#189]
Sometimes when saving a level, aborting, then loading the level again, it will play the wrong music track instead of the one the Level started with, this is most noticeable when making saves for any level past Yun's encounter. Top is Level 8's starting music, bottom is Level 8's track after saving & loading.

https://user-images.githubusercontent.com/19245505/212236281-168458a1-abe6-4e22-a9cc-477f2f5665ef.mp4

https://user-images.githubusercontent.com/19245505/212236288-da1c6084-b24d-4021-b5c7-ee6931ade25a.mp4

**Comment by shinyquagsire23** [comment]
Fixed v0.7.12
