### ISSUE TITLE
Force Blind overlay not working as intended

### ISSUE THREAD

**Issue by Journeyman716** [shinyquagsire23/OpenJKDF2#190]
Force Blinding doesn't make the screen white/fade from white, instead it overlays as a white-green that can be seen through, before suddenly turning purple and fading.

https://user-images.githubusercontent.com/19245505/212237613-be42ae92-cb3f-4de9-b61b-0240b20cfbfb.mp4

**Comment by shinyquagsire23** [comment]
Fixed v0.7.12. 

Though worth noting: The blinding overlay has always been white-green, I actually checked that at one point and it's just slightly off-white. At least on older CRTs you could kinda cheese the blinding by turning down the brightness a lot lol (or on TFT LCDs you could kinda tilt the screen back)
