### ISSUE TITLE
[Feature Request] Automatic updates

### ISSUE THREAD

**Issue by Vortikai** [shinyquagsire23/OpenJKDF2#194]
Optional automatic updates for OpenJKDF2. Why not?

**Comment by shinyquagsire23** [comment]
Yeah this is definitely something I've needed for a while, definitely before I pull MoTS out of Beta status

**Comment by Vortikai** [comment]
It would be an opportune time. I just updated the guides for JKGFXMOD on Steam for both JK and MOTS to use OpenJKDF2/OpenMOTS instead due to its simpler installation procedure, despite this being beta software, with warnings as such. I think this is a good move overall as it gives us more beta testers and it's user-friendly.

**Comment by shinyquagsire23** [comment]
Implemented v0.8.16, it uses Github's Releases API endpoint to check for updates. I also tried to make it fairly futureproof'd from the standpoint of like, if someone made a specific fork of OpenJKDF2 (or if my Github got nuked somehow), it can also point to different repos or mirrored JSONs.

**Comment by Vortikai** [comment]
That's really cool. My only concern is this probably doesn't work for how I got users installing OpenJKDF2 for Steam.

Currently, we rename openjkdf2.exe to JediKnight.exe so that we may launch through steam and get the Steam overlay. I am assuming the autoupdates will not detect this anomaly, and install as normal? If so, any thoughts on how to mitigate this if possible?

**Comment by shinyquagsire23** [comment]
@Vortikai ok the good (bad?) news is that I messed up my automatic updating on Win64 anyhow so the first real working autoupdate will have a fix for that now, lol

**Comment by Vortikai** [comment]
Most excellent. I assume this takes into consideration the naming conventions of Mysteries of the Sith on Steam being JediKnightM.exe instead of JediKnight.exe.

I'll close this for now and if I run into problems with the MOTS directory/install/updates, I'll open a new one. Thanks a bunch for finally getting this implemented!

**Comment by shinyquagsire23** [comment]
Yeah it uses whatever name the EXE was launched as, it's completely invariant. So JK.EXE, JediKnightM.exe, whatever.exe will all get updated from OpenJKDF2-64.exe in the update zip.
