### ISSUE TITLE
Transparent surfaces glitching when viewed through other transparent surfaces

### ISSUE THREAD

**Issue by Journeyman716** [shinyquagsire23/OpenJKDF2#196]
In OpenJK, transparent surfaces tend to bug out when looked at through each other, whereas in vanilla (jkgfxmod at least) it's just fine. Two examples showcasing it, one for water w/ vent in "Siege on Derra IV", and one for windows in "Dark Forces: Rebel Agent (MOTS)"

https://user-images.githubusercontent.com/19245505/213090283-c1e6147f-9042-4437-8791-c5757d00cba7.mp4

https://user-images.githubusercontent.com/19245505/213090354-27b13d60-fd63-41eb-9733-b3d4155970de.mp4

**Comment by shinyquagsire23** [comment]
Fixed v0.8.3
