### ISSUE TITLE
[MOTS] Main Menu button positions are inconsistent with vanilla

### ISSUE THREAD

**Issue by Journeyman716** [shinyquagsire23/OpenJKDF2#198]
In OJK, MOTS' button positioning on the main menu is the same as DF2, but vanilla MOTS actually adjusts it slightly because of the logo. Top is vanilla, bottom is OJK.
![image](https://user-images.githubusercontent.com/19245505/213260912-a52064c9-5e1c-481d-b9d1-f2d2bdb4a1dd.png)
![image](https://user-images.githubusercontent.com/19245505/213260932-0208fbff-319f-4156-825c-1508092d292e.png)

**Comment by shinyquagsire23** [comment]
Fixed v0.8.3
