### ISSUE TITLE
Unable to advance through menues using enter key

### ISSUE THREAD

**Issue by OCircles** [shinyquagsire23/OpenJKDF2#20]
The relevant ones are end level menus, where normally you can just hold down enter to quickly advance to the next level.

Another important one is the load menu. In the base game you'd buffer inputs from the load menu by pressing whatever input (usually LMB/RMB for thermal detonators that you have cooked so that they don't throw immediately on loading save)

Save menu saves on enter
Jedi powers menu exits out on enter
Options menu exits out on enter
Option sub-menues revert back to just the options menu on enter

**Comment by shinyquagsire23** [comment]
The next release w/ 2c81e918ed9a9fc97335e0984b17c859f07f870f should at least have the quick level advance + menuing, at least if I'm understanding the behavior you're describing. I might leave this issue open because my window event emulation doesn't really handle buffering at all, currently, and I'd probably have to get JK.EXE side by side to play with it to be certain that my implementation handles edges correctly.

**Comment by OCircles** [comment]
Ah, I wrote that pretty poorly. To clarify on the input buffering, you'd hold down some input in the load menu and then press enter-- this way the input happens immediately on going back in-game. Since people generally use LMB for primary fire, being able to use enter instead of clicking load button is required for this since, well, can't hold down LMB and click the load button at the same time.

Good for TD jumps that require cooked TD, this way you can quicksave with fully cooked TD :)

**Comment by shinyquagsire23** [comment]
Ahh ok, even still if you can hold enter to skip through the end of level menu, that would mean I need to be sending a WM_KEYFIRST event for every key currently down when going from gameplay -> menus (enter not working was just that I didn't send WM_KEYFIRST at all).

The current workaround-ish behavior in Setup submenus is that holding enter will continue falling through menus from one keypress (though not instantly, there's some delay), and holding enter while clicking the Jedi Powers menu will keep exiting. Maybe that's the same as the original, need to check.

**Comment by shinyquagsire23** [comment]
Fixed in v0.1.14
