### ISSUE TITLE
(Bug) the event console font size does not scale to the window size.

### ISSUE THREAD

**Issue by Alex3474247** [shinyquagsire23/OpenJKDF2#206]
As in the title, the font size does not scale to the size of the window and as a result, the game messages are cut off and do not fit into the screen (see the picture). Version 0.8.5.
![image_](https://user-images.githubusercontent.com/17110303/215167200-eaeefa03-035a-40ea-94b0-98f338e0eaaf.png)

**Comment by shinyquagsire23** [comment]
Worth noting, the HUD scale can be altered in Setup > Display so that it's not as large (also applies to the Quake-style console and inventory scrolls, though currently all overlay elements are tied to the same scale). I did fix this though for v0.8.6

**Comment by Alex3474247** [comment]
Tested, seems fixed v 0.8.6
