### ISSUE TITLE
Cooked thermal detonator doesn't behave as original

### ISSUE THREAD

**Issue by OCircles** [shinyquagsire23/OpenJKDF2#21]
In original you can start cooking a TD and not throw it by equipping some other weapon

In the original, if you save with a cooked TD it gets immediately thrown on load, unless you buffer primary/secondary fire input from the load menu or some other input that interrupts it, such as equipping weapons. In OpenJKDF2 it just remains cooked in your hand until you press fire again

**Comment by shinyquagsire23** [comment]
Fixed v0.2.2
