### ISSUE TITLE
Third-person idle rotating camera

### ISSUE THREAD

**Issue by Vortikai** [shinyquagsire23/OpenJKDF2#212]
The third-person idle rotating camera is either disabled or not working. In vanilla JK and MOTS, when the player idles for a minute or so, the player character begins idle animations while the camera rotates around the character model in third-person. This was done presumably in an attempt to mitigate issues from a bygone era of CRT burn-in. [v0.8.7](https://github.com/shinyquagsire23/OpenJKDF2/releases/tag/v0.8.7)

**Comment by Alex3474247** [comment]
By the way, yes, it doesn't work for me either.

**Comment by Vortikai** [comment]
Issue persists as of [v0.8.8](https://github.com/shinyquagsire23/OpenJKDF2/releases/tag/v0.8.8) on Jedi Knight only, tested using old profile with a new game level 1.

The issue is fixed in MOTS using the same procedure

**Comment by shinyquagsire23** [comment]
Fixed v0.8.13
