### ISSUE TITLE
Missing va_start/va_end wrapping in stdPlatform_Printf?

### ISSUE THREAD

**Issue by thecom** [shinyquagsire23/OpenJKDF2#213]
OpenJKDF2 crashed randomly for me. I think I traced the error to `stdPlatform_Printf()`. There both `vprintf()` and `vsnprintf()` seem to consume the variadic arguments. If I insert `va_end(args); va_start(args, fmt);` between both calls, the crashes stop.

I'm no C expert, does this make sense?

**Comment by shinyquagsire23** [comment]
Oh I actually just fixed this last night, it caused a crash on x86_64 Linux specifically for some reason

**Comment by shinyquagsire23** [comment]
Specifically though, bca3d9873538ab76dcfa64277c9fc243990b3ed2

**Comment by thecom** [comment]
Awesome, fix confirmed. Thanks a lot!
