### ISSUE TITLE
[MotS] Bonus Force Stars from finding secret areas aren't usable

### ISSUE THREAD

**Issue by Journeyman716** [shinyquagsire23/OpenJKDF2#214]
In MotS OJK, if you find all secret areas in a level, you're meant to get an extra force star to spend on force powers, but in OJK it's glitched every time, eg. Level 8 gives two stars on regular completion, three with all secret areas found, but you still only have two stars to spend in Force selection.

**Comment by shinyquagsire23** [comment]
Turns out, not a bug: The game keeps track of the total number of stars you're supposed to have, and level 8 forces you to take Force Pull. When it calculates how many stars in the star pool you can spend, it drops by one because of that forced spend.
