### ISSUE TITLE
Unclimbable ledge on Barons Hed

### ISSUE THREAD

**Issue by OCircles** [shinyquagsire23/OpenJKDF2#22]
[Original on the left, OpenJKDF2 on the right](https://streamable.com/58l6gn)

Not sure why this even works in the original, you clearly should not be able to make it up but there's some glitchy behavior here where it sort of transports you upwards automatically if you jump here. Use cheat "hyper 7" if you want to go check on it

**Comment by shinyquagsire23** [comment]
Hmmm I'll have to double check this one with frame limiting turned on, my ~guess is that it has to do with the player physics usually running at 50fps. There's a lot of generally odd sticking behavior with the physics at high framerates, usually around 45 degree slopes with multiple surfaces, but maybe the angle players stick gets steeper for lower framerates.

**Comment by shinyquagsire23** [comment]
Fixed 862e5112f31b39f0b11fa0af81e1dec430c5f023, and it actually works at high framerates as well surprisingly

**Comment by shinyquagsire23** [comment]
Implemented v0.2.10
