### ISSUE TITLE
Incorrect whitespace rendering in text on Raspberry Pi 4B

### ISSUE THREAD

**Issue by dborel** [shinyquagsire23/OpenJKDF2#220]
I built v0.8.8 for arvm71 after editing CMakeLists.txt to support CMake 3.16 and link stdc++fs. I also had to set MESA_GL_VERSION_OVERRIDE=3.3. But things generally work very well, with jkgm and hardware acceleration on the V3D! However, one minor issue is text. Each whitespace character is replaced by a square.
![WIN_20230203_08_23_07_Pro (2)](https://user-images.githubusercontent.com/3324766/216655537-1171493c-503d-4fcf-80e6-50942cebb3af.jpg)

**Comment by shinyquagsire23** [comment]
Is it on every string in the UI, or just those ones in particular? ie, do the original settings in General also have the boxes

**Comment by vrdaveb** [comment]
Every string. Also occurs with MOTS and LLVMPIPE.

**Comment by shinyquagsire23** [comment]
@dborel @vrdaveb maybe try on the latest commit? I can recreate the bug by forcing `_iswspace` in `src/jk.c` to always return 0, and I added some extra logic to maybe be explicit, idk though

**Comment by vrdaveb** [comment]
Thanks, that fixed it!
![20230204_220615](https://user-images.githubusercontent.com/6842123/216804543-a6c2bd3f-de9b-4389-abda-13b266680d5a.jpg)

**Comment by shinyquagsire23** [comment]
Fixed v0.8.10
