### ISSUE TITLE
Fail to build on Pi4/Buster 10

### ISSUE THREAD

**Issue by Exarkuniv** [shinyquagsire23/OpenJKDF2#225]
Im seeing if i can get this to work on my Pi4
Im running Buster 10 which is a 32bit OS

i tried 
``./build_linux64.sh``
``./build.sh``
```
mkdir -p build_blobs
cd build_blobs

cmake .. -DOPENJKDF2_USE_BLOBS=true
make -j10
```
```
mkdir -p build
cd build

cmake .. --toolchain ../cmake_modules/linux_32_toolchain.cmake
make -j10
```
all fail. 

i see that #220 got it working, but i dont know what he was talking about. and how he did it

the only one that gets far is the ``./build_linux64.sh``
but i end up getting this when it tries to link the binary 

https://pastebin.com/zSk0GMs5

any pointers would be great if it can made working on this OS

**Comment by shinyquagsire23** [comment]
I guess two things:

- Not sure why it's not setting the 2-byte wchar option for the output
- Did you make sure to set `CC=clang` and `CXX=clang++` as specified in BUILDING.md? Technically it can build with GCC, but historically GCC has tripped up more on optimizations.

**Comment by Exarkuniv** [comment]
yes both are set

heres the full command

```
export CC=clang
    export CXX=clang++

    chmod +x build_linux64.sh
    ./build_linux64.sh
```

**Comment by shinyquagsire23** [comment]
I think what you can do is add
```
target_link_libraries(${BIN_NAME} PRIVATE stdc++fs)
```
in this section here:
https://github.com/shinyquagsire23/OpenJKDF2/blob/master/CMakeLists.txt#L664

**Comment by shinyquagsire23** [comment]
Actually nvm I pushed a better fix I found, give the latest master a go

**Comment by Exarkuniv** [comment]
thank you for taking a look at this.
i did give it a shot with a fresh pull, and this is the error i got

https://pastebin.com/JkggYZC1

im still using this to build
```
export CC=clang
    export CXX=clang++

    chmod +x build_linux64.sh
    ./build_linux64.sh
```

**Comment by shinyquagsire23** [comment]
@Exarkuniv looks like it built successfully, the wchar_t warnings are mostly fine because I use my own stdlib implementations for those anyhow. So it should just be a matter of running `LD_LIBRARY_PATH=build_linux64 build_linux64/openjkdf2`

**Comment by Exarkuniv** [comment]
thanks for your help

im working on seeing if i can get this going. i used `` LD_LIBRARY_PATH=build_linux64 build_linux64/openjkdf2`` and it will say Recreating SDL2 Window

since im running this without a desktop i tried it with ``XINIT LD_LIBRARY_PATH=build_linux64 build_linux64/openjkdf2``
and i get ``No absolute path found for shell: LD_LIBRARY_PATH=build_linux64``

so i went into the build dir and ran sudo xinit ./openjkdf2 and i get a window with ``failed to initialize sdl opengl content could not create GL context: glxbadfbconfig"

is it because i used sudo?
im working through a terminal right now into my pi

**Comment by shinyquagsire23** [comment]
I'd say in general running as root is a bad idea because it'll mess with environment vars and stuff, but probably a good place to start would be making sure that `glxgears` runs correctly (ie, you have hardware acceleration working), then go from there. `LD_LIBRARY_PATH=build_linux64` has to be at the start of the line no matter the command you run, because it's just an environment variable setting. You might also have to set `DISPLAY`, ie `LD_LIBRARY_PATH=. DISPLAY=:0 sudo xinit ./openjkdf2`

**Comment by Exarkuniv** [comment]
i was able to run ``glxgears`` fine, i was the three colored gears and they where moving

but even with the new command 
it does try since i get Recreating SDL2 Window! text when i run it 

on my main display i still get
```
failed to initialize sdl opengl content 
could not create GL context: glxbadfbconfig
```

i just dont know what im missing that it will not start

**Comment by symbios24** [comment]
as i said before try this  
in buster edit config.txt and change the fkms to kms 

Maybe it will help

**Comment by Exarkuniv** [comment]
@symbios24 
and like with GTA, it doesnt help.
