### ISSUE TITLE
Idle camera not initiating

### ISSUE THREAD

**Issue by Vortikai** [shinyquagsire23/OpenJKDF2#229]
#212 states that the rotating idle camera has been fixed in JK in the latest version, but it still doesn't work for me.

**Comment by Journeyman716** [comment]
Weird because it works fine on my end with the latest build?

**Comment by shimstock22** [comment]
Also works for me. Sometimes his idle animation plays for a cycle before the camera rotated around him. Not sure if that is same as vanilla.

**Comment by shinyquagsire23** [comment]
fwiw there's definitely something funky going on w/ SDL, because what happened on my machine was the Insert key would get stuck down for no reason. So I might still have to tweak the behavior.

**Comment by shinyquagsire23** [comment]
Check and see if v0.8.14 is any better, I removed the extra anti-idle pokes so that it only applies to keybinds

**Comment by shimstock22** [comment]
Seems to be fixed for me! You're the man, Shiny

**Comment by Vortikai** [comment]
[v0.8.14](https://github.com/shinyquagsire23/OpenJKDF2/releases/tag/v0.8.14) fixed the idle camera issue on my end, and it seems to be working for others since the previous version.
