### ISSUE TITLE
Crash on entering tower area on Into the Dark Palace

### ISSUE THREAD

**Issue by OCircles** [shinyquagsire23/OpenJKDF2#23]
[Happens here consistently](https://streamable.com/5wkp9w)

--------------

Error occurred on Thursday, November 25, 2021 at 22:30:49.

openjkdf2-64.exe caused an Access Violation at location 00007FF73B281D4B in module openjkdf2-64.exe Reading from location FFFFFFFFFFFFFFFF.

AddrPC           Params
00007FF73B281D4B 000001C9DD8A3F50 000001C9DCC86D70 00007FF700000000  openjkdf2-64.exe!sithRender_RenderThings
00007FF73B27F254 00007FF73B3549E0 BA449BA600000001 3F9999993A449BA6  openjkdf2-64.exe!sithRender_Draw
00007FF73B26C5A2 00007FF73B3549A0 00007FF7437A0000 00007FF73B356EA0  openjkdf2-64.exe!sithCamera_SetRdCameraAndRenderidk
00007FF73B26A0C9 00007FF73B62FEA0 000001C9DF89EB30 0000000000000300  openjkdf2-64.exe!sith_UpdateCamera
00007FF73B2AD760 000000013B5CBF80 00007FF73B2B3CAF 00007FF73B5951B0  openjkdf2-64.exe!jkGame_Update
00007FF73B2B3949 0000000000000005 00007FF70000000F 0000000000000000  openjkdf2-64.exe!jkMain_GameplayTick
00007FF73B2B2F28 0000000000000000 00007FF90000000F 0000000000000000  openjkdf2-64.exe!jkMain_GuiAdvance
00007FF73B2CBD3C 0000000000000000 000000010000000F 0000000000000000  openjkdf2-64.exe!Window_Main_Loop
00007FF73B2CBF85 000001C900000001 000001C9D412AE40 000001C9D4350030  openjkdf2-64.exe!Window_Main_Linux
00007FF73B222C92 0000000000000001 000001C9D412AE40 0000000000000029  openjkdf2-64.exe!SDL_main
00007FF73B2FDDC1 0000000000000000 000000000000002A 00007FF73B630BB8  openjkdf2-64.exe!main_getcmdline  [/Users/valve/release/SDL/SDL2-2.0.16-source/foo-x64/../src/main/windows/SDL_windows_main.c @ 82]
00007FF73B2213C1 0000000000000000 0000000000000000 0000000000000000  openjkdf2-64.exe!__tmainCRTStartup
00007FF73B2214D6 0000000000000000 0000000000000000 0000000000000000  openjkdf2-64.exe!WinMainCRTStartup
00007FF953337034 0000000000000000 0000000000000000 0000000000000000  KERNEL32.DLL!BaseThreadInitThunk
00007FF953BC2651 0000000000000000 0000000000000000 0000000000000000  ntdll.dll!RtlUserThreadStart

openjkdf2-64.exe
ntdll.dll   	6.2.19041.1288
KERNEL32.DLL	6.2.19041.1348
KERNELBASE.dll	6.2.19041.1348
msvcrt.dll  	7.0.19041.546
SHELL32.dll 	6.2.19041.1320
msvcp_win.dll	6.2.19041.789
ucrtbase.dll	6.2.19041.789
USER32.dll  	6.2.19041.1202
OPENGL32.dll	6.2.19041.1081
win32u.dll  	6.2.19041.1320
ADVAPI32.dll	6.2.19041.1052
GDI32.dll   	6.2.19041.1202
sechost.dll 	6.2.19041.906
gdi32full.dll	6.2.19041.1110
RPCRT4.dll  	6.2.19041.1288
combase.dll 	6.2.19041.1348
exchndl.dll 	0.9.3.0
PSAPI.DLL   	6.2.19041.546
glew32.dll  	2.1.0.0
OpenAL32.dll	1.21.1.0
SDL2.dll    	2.0.16.0
SDL2_mixer.dll	2.0.4.0
ole32.dll   	6.2.19041.1202
IMM32.dll   	6.2.19041.546
OLEAUT32.dll	6.2.19041.985
mgwhelp.dll 	0.9.3.0
GLU32.dll   	6.2.19041.1081
SETUPAPI.dll	6.2.19041.1237
cfgmgr32.dll	6.2.19041.1151
VERSION.dll 	6.2.19041.546
WINMM.dll   	6.2.19041.546
bcrypt.dll  	6.2.19041.1023
dbghelp.dll 	10.0.19041.685
dbgcore.DLL 	10.0.19041.685
shcore.dll  	6.2.19041.1320
uxtheme.dll 	6.2.19041.1266
IconCodecService.dll	6.2.19041.1
WindowsCodecs.dll	6.2.19041.1151
kernel.appcore.dll	6.2.19041.546
bcryptPrimitives.dll	6.2.19041.1348
clbcatq.dll 	2001.12.10941.16384
MMDevApi.dll	6.2.19041.1023
DEVOBJ.dll  	6.2.19041.1151
avrt.dll    	6.2.19041.546
MSCTF.dll   	6.2.19041.1202
AppXDeploymentClient.dll	6.2.19041.1288
nvoglv64.dll	27.21.14.5671
WTSAPI32.dll	6.2.19041.546
msasn1.dll  	6.2.19041.546
cryptnet.dll	6.2.19041.906
CRYPT32.dll 	6.2.19041.1320
cryptbase.dll	6.2.19041.546
WINTRUST.dll	6.2.19041.1266
ntmarta.dll 	6.2.19041.546
dxcore.dll  	6.2.19041.546
windows.storage.dll	6.2.19041.1320
Wldp.dll    	6.2.19041.1320
shlwapi.dll 	6.2.19041.1023
dwmapi.dll  	6.2.19041.746
powrprof.dll	6.2.19041.546
UMPDC.dll
WINSTA.dll  	6.2.19041.546
textinputframework.dll	6.2.19041.1320
CoreUIComponents.dll	6.2.19041.546
CoreMessaging.dll	6.2.19041.746
WS2_32.dll  	6.2.19041.546
wintypes.dll	6.2.19041.1348
AUDIOSES.DLL	6.2.19041.1023
resourcepolicyclient.dll	6.2.19041.546
symsrv.dll  	10.0.19041.685
wininet.dll 	11.0.19041.1320
iertutil.dll	11.0.19041.1266
SspiCli.dll 	6.2.19041.1266
profapi.dll 	6.2.19041.844
ondemandconnroutehelper.dll	6.2.19041.546
winhttp.dll 	6.2.19041.1320
mswsock.dll 	6.2.19041.546
IPHLPAPI.DLL	6.2.19041.546
NSI.dll     	6.2.19041.610
WINNSI.DLL  	6.2.19041.546
urlmon.dll  	11.0.19041.1320
srvcli.dll  	6.2.19041.546
netutils.dll	6.2.19041.546
DNSAPI.dll  	6.2.19041.1320
rasadhlp.dll	6.2.19041.546
fwpuclnt.dll	6.2.19041.1348

Windows 6.2.9200
DrMingw 0.9.3

**Comment by shinyquagsire23** [comment]
Confirmed and should be fixed on the next release w/ dc4a2df09e1a6f366a2f6fbd686136f8e4fd60a6

**Comment by shinyquagsire23** [comment]
Fixed v0.1.13
