### ISSUE TITLE
Crash in rdVector in MotS level 8 droid room (read access violation)

### ISSUE THREAD

**Issue by Alex3474247** [shinyquagsire23/OpenJKDF2#232]
I have not made any changes to rdVector.c
The playthrough is stopped at this point, I'm not moving on.
If you open this door, on the picture, an exception occurs in rdVector.c, line 46 in rdVector_Copy3 (windows 10, 64 bit):
![image](https://user-images.githubusercontent.com/17110303/218329740-c0a159db-d70f-41ab-be45-25f16a56c85b.png)

Exception thrown: read access violation.
**v2** was 0x27CD1F7B760.
Exception thrown: read access violation.
**v2** was 0x1ED0D7D4430.
Unhandled exception thrown: read access violation.
**v2** was 0x27CD1F7B760.

>	openjkdf2-64.exe!rdVector_Copy3(rdVector3 * v1, const rdVector3 * v2) Line 46	C
 	openjkdf2-64.exe!rdPrimit3_ClipFaceRGBLevel(rdClipFrustum * clipFrustum, int geoMode, int lightMode, int texMode, rdVertexIdxInfo * idxInfo, rdMeshinfo * mesh_out, rdVector2 * idkIn) Line 1618	C
 	openjkdf2-64.exe!sithRender_RenderLevelGeometry(...) Line 1160	C
 	openjkdf2-64.exe!sithRender_Draw(...) Line 402	C
 	openjkdf2-64.exe!sithCamera_SetRdCameraAndRenderidk(...) Line 538	C
 	openjkdf2-64.exe!sithMain_UpdateCamera(...) Line 436	C
 	openjkdf2-64.exe!jkGame_Update(...) Line 166	C
 	openjkdf2-64.exe!jkMain_GameplayTick(int a2) Line 731	C
 	openjkdf2-64.exe!jkMain_GuiAdvance(...) Line 320	C
 	openjkdf2-64.exe!Window_Main_Loop(...) Line 1223	C
 	openjkdf2-64.exe!Window_Main_Linux(int argc, char * * argv) Line 1336	C
 	openjkdf2-64.exe!SDL_main(int argc, char * * argv) Line 313	C
 	openjkdf2-64.exe!main_getcmdline() Line 82	C
 	[External Code]

**Comment by Vortikai** [comment]
Is this the room with the gonk droid being tortured by lighting? It seems like it but I am not 100% sure.

Prior to OpenJKDF2, I think shiny had modded FOV and mipmap patches. For JK it worked flawlessly, but for MOTS for some reason when those FOV and/or mipmap patches were applied, there were two hard crashes (crashes that required completely unplugging the computer and back in again) found in the game. Both of them had to do with lightning generated by the environment.

One was on Level 9: New Republic Escort Ship where the bridge collapses and lighting is shooting every where, before Mara asked where an Astromech was.

The second is Level 8: Takara's Stronghold where the gonk droid is being tortured

https://youtu.be/NDRLLNBoPRQ?t=294

**Comment by Alex3474247** [comment]
Vortikai, yes.

**Comment by Vortikai** [comment]
Unable to reproduce using windows 11 64bit intel NVIDIA 2080ti w/ jkgfxmod enabled. I did discover another issue though while testing (#235).

**Comment by Vortikai** [comment]
What happens when you noclip 1 through the level?

**Comment by shinyquagsire23** [comment]
Try the latest master, apparently I had an off-by-one with one of my refactors.

**Comment by Alex3474247** [comment]
I'm gonna test it later, maybe today. I'll write if I get some new info.

**Comment by Alex3474247** [comment]
Thanks, Shiny, it seems that the issue is fixed.

**Comment by Alex3474247** [comment]
Fixed as far as I can test, and I'm now already at the beginning of level 12 of MotS, the walkthrough with not working blasters is somewhat boring, no more bugs detected.
