### ISSUE TITLE
Level 4 can't swim against the current LITERALLY.

### ISSUE THREAD

**Issue by wolfinston85** [shinyquagsire23/OpenJKDF2#238]
So I was playing on the most recent version after using the Force Engine with the original Dark Forces, great projects by the way -wished I was less broke so I could support you with something more tangible than compliments-, anywho, everything was going wonders for this when suddenly, at level 4 (the level where you first get the lightsaber) I couldn't swim against the current in the aqueducts, specifically in the one that leads to the grating of the first secret of the level. Here as a reference: [https://youtu.be/9pvk_BWKXtU?t=2722](url)

Is minute 45:22 in the video; I couldn't swim against the current as is presented in the video. Had to end up using the noclip command to make my way back; I'm using the latest Steam version with the latest version of the source port, Source port? I just changed the vsync option (which I enable) and some of the keyboard bindings; also set the game to run at fullscreen. I'm using 1080p as a res.

Either way, really hope you keep working on this, the titles are great and this is -really-, the best way to play these titles nowadaysh.

So, I'm just reporting it; see yah.

**Comment by Vortikai** [comment]
Unable to reproduce. [v0.8.14](https://github.com/shinyquagsire23/OpenJKDF2/releases/tag/v0.8.14) Win 11 NVIDIA 2090GT intel gsync enabled with "Restore inconsistent physics" "Restore 50Hzmidair player physics" unchecked.

**Comment by shinyquagsire23** [comment]
One thing to maybe check is if setting the frame limiter helps or not -- I've been meaning to get rid of the unlimited framelimit and just set it to 150Hz maximum, because if the time deltas get too small weird stuff happens.

**Comment by wolfinston85** [comment]
Manage to fix it!

I'm not using a Gsync monitor, my hz is 60; I managed to get past this by checking "Restore inconsistent physics" setting in advanced gameplay settings.

Vsync was on, turning it off didn't help, "50hzmidair" option didn't do a thing either, it was enabling the "inconsistent physics" setting the one that fixed it for me, so there.

Both "Restore 50hz midair" and "Restore inconsistent physics" options were disabled for me by default, it was by trying to turn them on or off that I ended up fixing the issue; narrowing it down to the "incosistent physics" option.

Thanks again for the port, it's great though, love the story and the gameplay still holds up pretty darn well, I also love the fact that the widescreen res doesn't change whenever I pause the game.

**Comment by shinyquagsire23** [comment]
still haven't been able to recreate this really, there does seem to be a weird spot right by the grating where you can standstill, but it's the same for me with both inconsistent and 150Hz physics (and in all cases, running instead of walking would get past it). One of these days I might try and make a test map to verify all of the physics are definitely the same tbh because I can see edge cases arising with the sector boundaries in the river (slopes had similar issues with pushback that could cause standstills at high fps, so it's not unprecedented)

**Comment by damnedhatter** [comment]
I also couldn't swim upstream, but setting "Restore inconsistent physics" worked.
