### ISSUE TITLE
Level 4 easter egg doesn't work in OpenJKDF2

### ISSUE THREAD

**Issue by LazyWizard** [shinyquagsire23/OpenJKDF2#239]
There's an obscure easter egg at the start of the level The Jedi's Lightsaber in the original game where if you kill your family droid Weegee, you instantly fall to the dark side.

In the original game, this scene displays the force power screen you'd normally see after the Maw fight where your light powers are stripped away alongside a short speech by Rahn.

In the current build of OpenJKDF2 (0.8.14) the Rahn voiceover plays upon Weegee's death, but your alignment and force powers remain unchanged.

**Comment by shinyquagsire23** [comment]
Wait wat lmao, I actually had no idea that was a thing. Not sure how I'd mess that up though but I can check.

**Comment by LazyWizard** [comment]
Yeah, it's incredibly obscure. When I discovered it as a bored kid I couldn't find a single mention of it anywhere. Even now I could only find it mentioned on a [single wiki page.](https://starwars.fandom.com/wiki/WeeGee#Behind_the_scenes)

For your own sanity, test with cheats and stacks of sequencers. The devs gave the droid a ridiculous pool of health. Whittling it down with the saber would take ages.

**Comment by shinyquagsire23** [comment]
ok I checked on the original game and it doesn't actually do the force screen, but the script does add 5 pedestrian deaths, which get added to the alignment at the end of the level. But also the Maw force screen actually doesn't strip the blue force powers anyhow, it only strips the light/dark ones which aren't obtainable at lv4.
