### ISSUE TITLE
Bowcaster being strange if equipped on load

### ISSUE THREAD

**Issue by OCircles** [shinyquagsire23/OpenJKDF2#25]
When loading a save or starting a level, it'll fire when you try to equip some other weapon after as if it was charged, except it only fires one projectile

**Comment by shinyquagsire23** [comment]
Should be fixed in the next release with c9fd48241773e4217c14d41111a9f2f209797e88, though because the bug was in save serialization you'll have to re-save for it to be fixed properly.

**Comment by shinyquagsire23** [comment]
Fixed v0.1.13
