### ISSUE TITLE
Screenshots unimplemented on Linux?

### ISSUE THREAD

**Issue by JPLeBreton** [shinyquagsire23/OpenJKDF2#251]
I'm running latest on Manjaro Linux and when I press F12 in-game, a "Screenshot Taken" message appears on-screen but in the terminal output, it says "TODO: Implement screenshots", and I don't see any screenshot files appear anywhere (unless it's somewhere besides the build directory or ~/.local/share/openjkdf2/). Other issues in this tracker here imply that screenshots are working in Windows, so are they just not implemented in Linux?

**Comment by shinyquagsire23** [comment]
Is there a version in the bottom-left corner of your title screen? It should be implemented on every platform that has JKGM support.

**Comment by JPLeBreton** [comment]
> Is there a version in the bottom-right corner of your title screen? It should be implemented on every platform that has JKGM support.

I don't see numbers on any of the menu screens (or during the opening cutscene). I also don't see the version number in the terminal output; I'm used to seeing it there at least. When I run `./openjkdf2-64 --version` it prints this, but that's obviously the original game version (read the resource files, I assume? or maybe from the original game source/symbols?):
```
Dark Forces II: Jedi Knight v1.00
(c) 1997 Lucasfilm Ltd. and LucasArts Entertainment Company. All Rights Reserved.Built Sep 10 1997 09:39:21
```

This version is the latest git master branch (I rebuilt today just to make sure), built with the `build_linux64.sh` script and run from the build subdirectory.

**Comment by shinyquagsire23** [comment]
It would have to be outdated if it's still doing the TODO print, it's commented out on the latest master. Another smoking gun would be if the Quake console is missing (press the \`~ key). Maybe double check modification dates or re-clone?

**Comment by JPLeBreton** [comment]
> It would have to be outdated if it's still doing the TODO print, it's commented out on the latest master. Another smoking gun would be if the Quake console is missing (press the `~ key). Maybe double check modification dates or re-clone?

Ah, yes it seems I was indeed using an old version - I did a re-clone in a fresh directory, rebuilt, and now have a visible version number, screenshot support, etc. So this issue can be closed.

The odd thing is that as far as git could tell before I did that, I was using the very latest pull of the git master branch. I think I'd first cloned the project sometime in August of 2022. What's the equivalent of `make clean` in this project's build system?

**Comment by shinyquagsire23** [comment]
For my versioned releases I delete the build_whatever folder and then reconfigure, I've had CMake get stuck when I tried doing make clean. Too many dependencies and not worth the headache usually, and on macOS/Linux if you update packages the pkgconfig stuff will get stuck on old versions too.
