### ISSUE TITLE
Thrown secondary fire thermal detonator doesn't behave as original

### ISSUE THREAD

**Issue by OCircles** [shinyquagsire23/OpenJKDF2#26]
In original, a thrown secondary fire TD will normally not interact with the player, but if you save and load after having thrown it'll then explode when touching Kyle as if it was thrown by an enemy

In OpenJKDF2, after loading the save you can now push around the TD as if it were a physics object. Does not explode on contact

**Comment by shinyquagsire23** [comment]
Fixed w/ df76e180ade57e8e1a3e7c17b22ec3666ed8e308, the bug was actually a pretty serious one and might have had other effects. 

Also apparently the reason for this behavior is that saves don't serialize the parent of the detonator thing (or any things) which is an interesting oversight.

**Comment by shinyquagsire23** [comment]
Fixed in v0.1.14
