### ISSUE TITLE
Performance issues on full screen

### ISSUE THREAD

**Issue by SlightPersimmon1** [shinyquagsire23/OpenJKDF2#261]
Hi all

I'm having performance issues when setting the game to run at full screen. At first this could have a simple answer: my machine is not good enough to run it at full screen because of optimization issues of the engine, But strangely enough, disabling full screen and playing the game with the window maximized solves the issue entirely and i have a smooth gameplay with this setting.

Windows 8.1
Geforce GTX 960
Playing at 1680x1050

**Comment by shinyquagsire23** [comment]
This might be fixed on v0.9.0?
