### ISSUE TITLE
MOTS - Level 14 - blocker - not possible to finish

### ISSUE THREAD

**Issue by mikesk8** [shinyquagsire23/OpenJKDF2#275]
Good morning, 

I have just arrived to almost the end of the Level 14 in MOTS and I believe something is wrong that prevents to finish the level. 

Basically, you get to big doors with statues by them in the main huge chamber; there should be small pictures of the saberists on both sides and switch, but they are missing. You can see something is missing in the textures as the shapes are there - please see attached picture.

I use latest version 0.9.0 on Mac.

Have a good summer day, M.
<img width="2560" alt="Screenshot 2023-08-03 at 11 46 14" src="https://github.com/shinyquagsire23/OpenJKDF2/assets/46671688/236be0fc-3891-44e5-a853-1531d9faa31f">

**Comment by mikesk8** [comment]
One more, the actual door texture (to the right of the switch - pls see picture above) is missing as well.

**Comment by shinyquagsire23** [comment]
tbh I've had a lot of issues with the last level and I'm not ~totally sure how many of them are issues w/ OpenJKDF2 and how many are just issues in the base game, bc it seems even speedrunners have commented that the level is kinda jank

**Comment by mikesk8** [comment]
Thanks for the answer. In general, I had rather ok experience in this last level; some small glitches not worth mentioning; till the moment I cannot progress as the doors/buttons are not there :( 

Please let me know how can I help you to test/analyze it?

**Comment by shinyquagsire23** [comment]
if you have a savegame for the glitch I could take a look at it, however you'll also have to let me know if you have any mods installed

**Comment by mikesk8** [comment]
Super, I have a savegame just before the glitch and my game is without any mods; basically default settings.

I will send you the file after holidays :-)

**Comment by mikesk8** [comment]
I am back :-) Here is the save file (called M2); you will be just in front of the missing elements as described in the first two posts above. I don't have any mods installed; clean install. 

Thanks a lot and please let me know if testing is needed ;)

[msav0002.jks.zip](https://github.com/shinyquagsire23/OpenJKDF2/files/12495837/msav0002.jks.zip)

**Comment by mikesk8** [comment]
Good morning ;-) Please let me if you need any help in testing ;-) It could be great to be able to finish the game.

**Comment by shinyquagsire23** [comment]
ok so, I hunted it down and it looks like the panels are locked based on the two doors on the platform to the left not being open

<img width="752" alt="Screenshot 2023-09-11 at 1 28 08 PM" src="https://github.com/shinyquagsire23/OpenJKDF2/assets/1224096/fb7cddf0-7ad1-4821-aebe-e2132592b044">
<img width="752" alt="Screenshot 2023-09-11 at 1 29 35 PM" src="https://github.com/shinyquagsire23/OpenJKDF2/assets/1224096/fc218103-a868-47ee-bf87-a3ff1d0a3572">

As far as I can tell, the issue is that you didn't double back and explore the right branch at the start of the level, there's a lot of unpressed buttons
