### ISSUE TITLE
crash when pressing OK button after entering name

### ISSUE THREAD

**Issue by farmboy0** [shinyquagsire23/OpenJKDF2#28]
Build commit: f9de84ba3c93d37ffc8230b718548fe827ff7d31

Stacktrace from openjkdf2:
BACKTRACE:
----------------------
./openjkdf2-64(print_backtrace+0xd6) [0x4fb326]
./openjkdf2-64(crash_handler_basic+0x6) [0x4fb6d6]
/lib64/libc.so.6(+0x38ba0) [0x7f603770bba0]
./openjkdf2-64() [0x401480]
./openjkdf2-64(jkGuiPlayer_ShowNewPlayer+0x5e7) [0x621cf7]
./openjkdf2-64(jkGuiMain_Show+0x58) [0x61ea38]
./openjkdf2-64(jkMain_GuiAdvance+0x296) [0x652de6]
./openjkdf2-64(Window_Main_Linux+0x940) [0x6b27f0]
./openjkdf2-64(main+0x3b) [0x4fb73b]
/lib64/libc.so.6(__libc_start_main+0xcd) [0x7f60376f67fd]
./openjkdf2-64(_start+0x2a) [0x44b8ba]

Backtrace from gdb:
#0  0x0000000000401480 in ?? ()
#1  0x00000000006b56e0 in jkPlayer_CreateConf (name=0x1405620 <word_555D28> L"\105", <incomplete sequence \156>)
    at src/World/jkPlayer.c:179
#2  0x0000000000621cf7 in jkGuiPlayer_ShowNewPlayer (a1=1) at src/Gui/jkGUIPlayer.c:314
#3  0x000000000061ea38 in jkGuiMain_Show () at src/Gui/jkGUIMain.c:67
#4  0x0000000000652de6 in jkMain_GuiAdvance () at src/Main/jkMain.c:176
#5  0x00000000006b27f0 in Window_Main_Loop () at src/Win95/Window.c:756
#6  Window_Main_Linux (argc=<optimized out>, argv=<optimized out>) at src/Win95/Window.c:843
#7  0x00000000004fb73b in main (argc=1, argv=0x7fffffffd288) at src/main.c:345

**Comment by shinyquagsire23** [comment]
Fixed v0.1.15
