### ISSUE TITLE
the code execution cannot proceed because MSVCR120.dll was not found. Reinstalling the program may fix this problem." at top of box openjkdf2-64.exe

### ISSUE THREAD

**Issue by grfffffff3534hfdh37gfffdg** [shinyquagsire23/OpenJKDF2#282]
the code execution cannot proceed because MSVCR120.dll was not found. Reinstalling the program may fix this problem." at top of box openjkdf2-64.exe

**Comment by snaylor596** [comment]
How did you fix this?
