### ISSUE TITLE
crash when entering mouse menu

### ISSUE THREAD

**Issue by farmboy0** [shinyquagsire23/OpenJKDF2#29]
Build commit: fa14b618e45f1c2a50b223681885a59a5ff1433b

Stacktrace:
#0  0x00000000004178d0 in ?? ()
#1  0x0000000000630c9c in jkGuiSetup_Show () at src/Gui/jkGUISetup.c:124
#2  0x000000000061b74f in jkGuiEsc_Show () at src/Gui/jkGUIEsc.c:151
#3  0x00000000006528a6 in jkMain_GuiAdvance () at src/Main/jkMain.c:176
#4  0x00000000006b22b0 in Window_Main_Loop () at src/Win95/Window.c:756
#5  Window_Main_Linux (argc=<optimized out>, argv=<optimized out>) at src/Win95/Window.c:843
#6  0x00000000004fb73b in main (argc=1, argv=0x7fffffffd258) at src/main.c:345

**Comment by shinyquagsire23** [comment]
Implemented v0.1.16
