### ISSUE TITLE
Build fails on windows (visual studio)

### ISSUE THREAD

**Issue by archanaid** [shinyquagsire23/OpenJKDF2#295]
Hi,

Thank you for the project! I built it on Linux but having some issues building it using Visual studio on Windows. I've followed the instructions (dependencies and build step using Visual studio).

I'm getting some errors (tested on both Windows 10 and 11):

`
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB8066	Custom build for 'D:\My files\joja\sith\OpenJKDF2\build\libpng\CMakeFiles\2758899b1e3039666ad7ec03439e2b03\pnglibconf.c.rule;D:\My files\joja\sith\OpenJKDF2\build\libpng\CMakeFiles\2046fb408b2adb15a85279fe87d895b2\pnglibconf_c.rule;D:\My files\joja\sith\OpenJKDF2\lib\libpng\CMakeLists.txt' exited with code 1. [D:\My files\joja\sith\OpenJKDF2\build\libpng\pnglibconf_c.vcxproj]	LIBPNG	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets	248	
Error	MSB8066	Custom build for 'D:\My files\joja\sith\OpenJKDF2\build\libpng\CMakeFiles\db147fcc6561886e6af0da5f5b2ae1e7\pnglibconf.c.rule;D:\My files\joja\sith\OpenJKDF2\build\libpng\CMakeFiles\2046fb408b2adb15a85279fe87d895b2\scripts_pnglibconf_c.rule;D:\My files\joja\sith\OpenJKDF2\lib\libpng\CMakeLists.txt' exited with code 1. [D:\My files\joja\sith\OpenJKDF2\build\libpng\scripts_pnglibconf_c.vcxproj]	LIBPNG	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets	248	
Error	MSB8066	Custom build for 'D:\My files\joja\sith\OpenJKDF2\build\CMakeFiles\f2af75d7d76c2e3156d23158df099577\LIBPNG-mkdir.rule;D:\My files\joja\sith\OpenJKDF2\build\CMakeFiles\f2af75d7d76c2e3156d23158df099577\LIBPNG-download.rule;D:\My files\joja\sith\OpenJKDF2\build\CMakeFiles\f2af75d7d76c2e3156d23158df099577\LIBPNG-patch.rule;D:\My files\joja\sith\OpenJKDF2\build\CMakeFiles\f2af75d7d76c2e3156d23158df099577\LIBPNG-configure.rule;D:\My files\joja\sith\OpenJKDF2\build\CMakeFiles\f2af75d7d76c2e3156d23158df099577\LIBPNG-build.rule;D:\My files\joja\sith\OpenJKDF2\build\CMakeFiles\f2af75d7d76c2e3156d23158df099577\LIBPNG-install.rule;D:\My files\joja\sith\OpenJKDF2\build\CMakeFiles\ea76b44389353ca1b95ec227acbf9df1\LIBPNG-complete.rule;D:\My files\joja\sith\OpenJKDF2\build\CMakeFiles\1a740aec8ae23831a4c62d66b0e6a4f2\LIBPNG.rule;D:\My files\joja\sith\OpenJKDF2\CMakeLists.txt' exited with code 1.	LIBPNG	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets	248	
Error	MSB8066	Custom build for 'D:\My files\joja\sith\OpenJKDF2\build\CMakeFiles\f20cac40f5ad3178d4acb11b6250f41d\.copied_hack.rule;D:\My files\joja\sith\OpenJKDF2\build\CMakeFiles\1a740aec8ae23831a4c62d66b0e6a4f2\GNS_HACK_ZLIB.rule;D:\My files\joja\sith\OpenJKDF2\CMakeLists.txt' exited with code 1.	GNS_HACK_ZLIB	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets	248	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libprotobufd.lib(common.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libprotobufd.lib(arenastring.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libprotobufd.lib(unknown_field_set.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libprotobufd.lib(message_lite.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libprotobufd.lib(repeated_field.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libprotobufd.lib(message.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libprotobufd.lib(repeated_ptr_field.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libprotobufd.lib(text_format.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libprotobufd.lib(coded_stream.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libprotobufd.lib(generated_message_reflection.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libprotobufd.lib(parse_context.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libprotobufd.lib(generated_message_util.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libprotobufd.lib(wire_format.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libprotobufd.lib(arena.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libprotobufd.lib(wire_format_lite.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libprotobufd.lib(stringpiece.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libprotobufd.lib(status.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libprotobufd.lib(strutil.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libprotobufd.lib(int128.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libprotobufd.lib(zero_copy_stream_impl_lite.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libprotobufd.lib(zero_copy_stream.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libprotobufd.lib(zero_copy_stream_impl.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libprotobufd.lib(descriptor.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libprotobufd.lib(reflection_ops.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libprotobufd.lib(map_field.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libprotobufd.lib(implicit_weak_message.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libprotobufd.lib(any_lite.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libprotobufd.lib(any.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libprotobufd.lib(tokenizer.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libprotobufd.lib(dynamic_message.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libprotobufd.lib(strtod.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libprotobufd.lib(extension_set_heavy.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libprotobufd.lib(extension_set.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libprotobufd.lib(structurally_valid.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libprotobufd.lib(io_win32.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libprotobufd.lib(descriptor.pb.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libprotobufd.lib(stringprintf.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libprotobufd.lib(substitute.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libprotobufd.lib(descriptor_database.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libprotobufd.lib(map.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libcpmtd.lib(locale0.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libcpmtd.lib(locale.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libcpmtd.lib(iosptrs.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libcpmtd.lib(wlocale.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libcpmtd.lib(xlocale.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libcpmtd.lib(xstol.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libcpmtd.lib(xstoul.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libcpmtd.lib(xstoll.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libcpmtd.lib(xstoull.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libcpmtd.lib(xlock.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libcpmtd.lib(xstrcoll.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libcpmtd.lib(xdateord.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libcpmtd.lib(xwcscoll.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libcpmtd.lib(xwcsxfrm.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libcpmtd.lib(xstrxfrm.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libcpmtd.lib(xmtx.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libcpmtd.lib(StlCompareStringA.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libcpmtd.lib(StlCompareStringW.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libcpmtd.lib(StlLCMapStringW.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in steamid.obj [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\libcpmtd.lib(StlLCMapStringA.obj)	1	
Error	LNK1319	60 mismatches detected [D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\src\GameNetworkingSockets.vcxproj]	GAMENETWORKINGSOCKETS	D:\My files\joja\sith\OpenJKDF2\build\GameNetworkingSockets\bin\Debug\GameNetworkingSockets.dll	1	
Error	MSB8066	Custom build for 'D:\My files\joja\sith\OpenJKDF2\build\CMakeFiles\740f6c779e7e9f247572cf4730f9f7da\GAMENETWORKINGSOCKETS-mkdir.rule;D:\My files\joja\sith\OpenJKDF2\build\CMakeFiles\740f6c779e7e9f247572cf4730f9f7da\GAMENETWORKINGSOCKETS-download.rule;D:\My files\joja\sith\OpenJKDF2\build\CMakeFiles\740f6c779e7e9f247572cf4730f9f7da\GAMENETWORKINGSOCKETS-patch.rule;D:\My files\joja\sith\OpenJKDF2\build\CMakeFiles\740f6c779e7e9f247572cf4730f9f7da\GAMENETWORKINGSOCKETS-configure.rule;D:\My files\joja\sith\OpenJKDF2\build\CMakeFiles\740f6c779e7e9f247572cf4730f9f7da\GAMENETWORKINGSOCKETS-build.rule;D:\My files\joja\sith\OpenJKDF2\build\CMakeFiles\740f6c779e7e9f247572cf4730f9f7da\GAMENETWORKINGSOCKETS-install.rule;D:\My files\joja\sith\OpenJKDF2\build\CMakeFiles\ea76b44389353ca1b95ec227acbf9df1\GAMENETWORKINGSOCKETS-complete.rule;D:\My files\joja\sith\OpenJKDF2\build\CMakeFiles\1a740aec8ae23831a4c62d66b0e6a4f2\GAMENETWORKINGSOCKETS.rule;D:\My files\joja\sith\OpenJKDF2\CMakeLists.txt' exited with code 1.	GAMENETWORKINGSOCKETS	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets	248	
Error	C2078	too many initializers	sith_engine	D:\My files\joja\sith\OpenJKDF2\src\Gui\jkGUIJoystick.c	140	
Error	C2078	too many initializers	sith_engine	D:\My files\joja\sith\OpenJKDF2\src\Gui\jkGUIJoystick.c	41	
Error	LNK1104	cannot open file 'SDL2main.lib'	openjkdf2-64	D:\My files\joja\sith\OpenJKDF2\build\LINK	1	
`

**Comment by bahstrike** [comment]
running vs2022 i also cannot build.   still able to build a checkout from like a year ago.

[rebuild all.txt](https://github.com/shinyquagsire23/OpenJKDF2/files/14146735/rebuild.all.txt)

**Comment by shinyquagsire23** [comment]
Fixed maybe idk
