### ISSUE TITLE
'Could not load level!' in Multiplayer

### ISSUE THREAD

**Issue by robrich82** [shinyquagsire23/OpenJKDF2#297]
I'm running 0.9.1 on Windows 11, when I try and load any multiplayer level in DF2 or MOTS I get the message 'Could not load level!' and the following error in the console

`(00007ff678ca3310 .\World\sithWorld.c:276) Failed to open file 'jkl\'.`

**Comment by ryanmilke** [comment]
I'm seeing this as well on Windows and macOS. I've reverted back to 0.9.0 for how, which works well.

**Comment by shinyquagsire23** [comment]
Yeah I fixed this bug and was hoping to fix some other MP bugs before making a new release, but yeah reverting is fine in the meantime

**Comment by ryanmilke** [comment]
Thank you! This project has already provided many hours of fun for my son and I in multiplayer. If you ever opened a Patreon or similar I'd love to contribute to the project.

**Comment by shinyquagsire23** [comment]
Fixed v0.9.2
