### ISSUE TITLE
crash when entering display menu

### ISSUE THREAD

**Issue by farmboy0** [shinyquagsire23/OpenJKDF2#30]
Stacktrace:
#0  0x0000000000414a10 in ?? ()
#1  0x0000000000630cfa in jkGuiSetup_Show () at src/Gui/jkGUISetup.c:100
#2  0x000000000061e427 in jkGuiMain_Show () at src/Gui/jkGUIMain.c:95
#3  0x00000000006528a6 in jkMain_GuiAdvance () at src/Main/jkMain.c:176
#4  0x00000000006b22b0 in Window_Main_Loop () at src/Win95/Window.c:756
#5  Window_Main_Linux (argc=<optimized out>, argv=<optimized out>) at src/Win95/Window.c:843
#6  0x00000000004fb73b in main (argc=1, argv=0x7fffffffd288) at src/main.c:345

**Comment by shinyquagsire23** [comment]
Fixed v0.2.1
