### ISSUE TITLE
Music Track order

### ISSUE THREAD

**Issue by nitro322** [shinyquagsire23/OpenJKDF2#300]
I think the README is wrong regarding music track order.  Would like to clarify, please.

Per the README:  ```"MUSIC/1/Track<1..11>.ogg and MUSIC/2/Track<1..11>.ogg"```

I interpret that to mean the first audio track from disc 1 becomes "MUSIC/Track1.ogg", the third track from disc 2 becomes "MUSIC/Track3.ogg", etc.  Please correct me if I have this basic part wrong, but assuming that's correct, I think there are two issues:

1. My discs contain only 7 music tracks on disc 1 and 11 tracks on disc 2.  So I think that should be "MUSIC/1/Track<1..7>.ogg and MUSIC/2/Track<1..11>.ogg", right?

2. It seems like the tracks should be numbered from 2-8 and 2-12 to match the original disks, since track 1 on each disc is the data track.  It seems the engine actually expects this:

```jkEpisode_Load: Seeing CD number >1 (2), assuming this is an OG disk install with offsetted tracks...```

And indeed the first track that gets played appears to be disc 1 track 2 rather than track 1:

```stdMci: Playing music `MUSIC/1/Track2.ogg'```

Maybe that's expected behavior.  I don't have an easy way to play the original game to compare, but I downloaded the [High Quality Music Pack](https://community.pcgamingwiki.com/files/file/2197-jedi-knight-dark-forces-ii-various-patches), which has the tracks pre-named for the GOG release (```MUSIC/Track<12..32>.ogg```), and OpenJKDF2 begins with track 12:

```
stdMci: Error in Mix_LoadMUS, Couldn't open 'MUSIC/1/Track2.ogg'
stdMci: Error in Mix_LoadMUS, Couldn't open 'MUSIC/1/Track02.ogg'
stdMci: Playing music `MUSIC/Track12.ogg'
```

This track 12 matches up the first audio track on disc 1.

So, I believe the documentation should state the following to match the actual behavior:

```"MUSIC/1/Track<2..8>.ogg and MUSIC/2/Track<2..12>.ogg"```

Can you confirm if that's correct, please?

**Comment by shinyquagsire23** [comment]
yeah that's correct, couldn't hurt to clarify that
