### ISSUE TITLE
Trying to Launch a level from Debug menu crashes game Version v0.9.1

### ISSUE THREAD

**Issue by GeneralTantor** [shinyquagsire23/OpenJKDF2#303]
For some reason any level I try to open from the Debug menu crashes the game... Is debug menu not suppose to be there? This did not happen in older versions though... 

Error Log:
-------------------

Error occurred on Monday, February 19, 2024 at 06:16:56.

JediKnight.exe caused an Integer division by zero at location 00007FF66A9FF51F in module JediKnight.exe.

AddrPC           Params
00007FF66A9FF51F 000000003F000000 00007FF66AD9C14E 000000DC5963F1B0  JediKnight.exe!sithSurface_Tick
00007FF66A9DB40F 00007FF66B119C8C 00007FF66B119CB8 0000000000000001  JediKnight.exe!sithMain_Tick
00007FF66A9D42CF 0000000000000000 0000000000000000 0000000000000000  JediKnight.exe!jkMain_GameplayTick
00007FF66A9F04A5 000000DC002E3A46 000000DC5963F6A8 0000021D579BD010  JediKnight.exe!Window_Main_Linux
00007FF66A9416EB 0000000000000001 0000000000000000 0000000000000001  JediKnight.exe!SDL_main
00007FF66ACC8434 0000000000000000 0000000000000045 00007FF66B66EB38  JediKnight.exe!main_getcmdline
00007FF66A9412EE 0000000000000000 0000000000000000 0000000000000000  JediKnight.exe!__tmainCRTStartup
00007FF66A9413E6 0000000000000000 0000000000000000 0000000000000000  JediKnight.exe!WinMainCRTStartup
00007FFF775F7344 0000000000000000 0000000000000000 0000000000000000  KERNEL32.DLL!BaseThreadInitThunk
00007FFF792826B1 0000000000000000 0000000000000000 0000000000000000  ntdll.dll!RtlUserThreadStart

JediKnight.exe	0.9.1.0
ntdll.dll   	10.0.19041.3996
KERNEL32.DLL	10.0.19041.3636
KERNELBASE.dll	10.0.19041.3996
ADVAPI32.dll	10.0.19041.3930
msvcrt.dll  	7.0.19041.3636
sechost.dll 	10.0.19041.3930
RPCRT4.dll  	10.0.19041.3758
bcrypt.dll  	10.0.19041.3636
GDI32.dll   	10.0.19041.3996
win32u.dll  	10.0.19041.3996
gdi32full.dll	10.0.19041.3996
msvcp_win.dll	10.0.19041.3636
ucrtbase.dll	10.0.19041.3636
USER32.dll  	10.0.19041.3996
IMM32.dll   	10.0.19041.3996
ole32.dll   	10.0.19041.3636
combase.dll 	10.0.19041.3636
OLEAUT32.dll	10.0.19041.3636
MSVCR120.dll	12.0.40664.0
SETUPAPI.dll	10.0.19041.3996
cfgmgr32.dll	10.0.19041.3996
OPENGL32.dll	10.0.19041.3636
SHELL32.dll 	10.0.19041.3996
GLU32.dll   	10.0.19041.3636
WS2_32.dll  	10.0.19041.3636
libssp-0.dll
VERSION.dll 	10.0.19041.3636
OpenAL32.dll	1.23.1.0
WINMM.dll   	10.0.19041.3636
CRYPTSP.dll 	10.0.19041.3636
rsaenh.dll  	10.0.19041.3636
CRYPTBASE.dll	10.0.19041.3636
bcryptPrimitives.dll	10.0.19041.3636
shcore.dll  	10.0.19041.3636
exchndl.dll 	0.9.3.0
PSAPI.DLL   	10.0.19041.3636
mgwhelp.dll 	0.9.3.0
dbghelp.dll 	10.0.19041.3636
dbgcore.DLL 	10.0.19041.3636
uxtheme.dll 	10.0.19041.3996
IconCodecService.dll	10.0.19041.1
WindowsCodecs.dll	10.0.19041.3636
mscms.dll   	10.0.19041.3636
USERENV.dll 	10.0.19041.3636
ColorAdapterClient.dll	10.0.19041.3636
icm32.dll   	10.0.19041.3636
kernel.appcore.dll	10.0.19041.3758
clbcatq.dll 	2001.12.10941.16384
MMDevApi.dll	10.0.19041.3636
DEVOBJ.dll  	10.0.19041.3996
avrt.dll    	10.0.19041.3636
hid.dll     	10.0.19041.3636
WINTRUST.dll	10.0.19041.3996
CRYPT32.dll 	10.0.19041.3636
MSASN1.dll  	10.0.19041.3636
dinput8.dll 	10.0.19041.1
inputhost.dll	10.0.19041.3636
PROPSYS.dll 	7.0.19041.3636
CoreMessaging.dll	10.0.19041.3930
CoreUIComponents.dll	10.0.19041.3636
wintypes.dll	10.0.19041.3636
ntmarta.dll 	10.0.19041.3636
Windows.Gaming.Input.dll	10.0.19041.3996
twinapi.appcore.dll	10.0.19041.3758
MSCTF.dll   	10.0.19041.3636
AppXDeploymentClient.dll	10.0.19041.3636
nvoglv64.dll	31.0.15.3713
WTSAPI32.dll	10.0.19041.3636
cryptnet.dll	10.0.19041.3636
drvstore.dll	10.0.19041.3636
wldp.dll    	10.0.19041.3996
windows.storage.dll	10.0.19041.3996
shlwapi.dll 	10.0.19041.3636
dxcore.dll  	10.0.19041.3996
nvspcap64.dll	3.27.0.112
profapi.dll 	10.0.19041.3636
dwmapi.dll  	10.0.19041.3636
powrprof.dll	10.0.19041.3636
UMPDC.dll
WINSTA.dll  	10.0.19041.3636
textinputframework.dll	10.0.19041.3996
Oleacc.dll  	7.2.19041.3636
libGameNetworkingSockets.dll
IPHLPAPI.DLL	10.0.19041.3636
AUDIOSES.DLL	10.0.19041.3636
resourcepolicyclient.dll	10.0.19041.3636
mswsock.dll 	10.0.19041.3636
DNSAPI.dll  	10.0.19041.4046
NSI.dll     	10.0.19041.3636
fwpuclnt.dll	10.0.19041.3758
rasadhlp.dll	10.0.19041.3636

Windows 10.0.19045
DrMingw 0.9.3

**Comment by JohnBillington** [comment]
Can confirm this is happening on my end as well

**Comment by GeneralTantor** [comment]
Granted I am using a bunch of mods will try it without the mods installed....

**Comment by JohnBillington** [comment]
> Granted I am using a bunch of mods will try it without the mods installed....

No mods on my end for what it’s worth

**Comment by shinyquagsire23** [comment]
Fixed v0.9.5
