### ISSUE TITLE
Physics Tickrate

### ISSUE THREAD

**Issue by JohnBillington** [shinyquagsire23/OpenJKDF2#305]
Is there a way that we can change the physics tickrate to match our display refresh via console command? If not, can we get this feature? It has been very successful in eliminating judder on the Nightdive DF Remaster

**Comment by shinyquagsire23** [comment]
Oh right that would be General > Advanced > Restore inconsistent physics, it's tricky though because there's side effects if you don't cap FPS or if FPS dips.

**Comment by JohnBillington** [comment]
Thank you so much
