### ISSUE TITLE
Some help!!

### ISSUE THREAD

**Issue by darkstar252** [shinyquagsire23/OpenJKDF2#31]
I can compile on my manjaro OpenJKDF2 but i gave this error message when launching:

FATAL ERROR: ERR_CANNOT_LOAD_FILE ui\sft\small0.sft

**Comment by farmboy0** [comment]
you need to make sure the file case is correct, see the readme

**Comment by darkstar252** [comment]
Ok i reviewed the file case , and according to the readme is ok. What is wrong here??

**Comment by darkstar252** [comment]
Ok i explain me.

I have the original release of Jedi Knight on 3 CD-ROM 2 CD's for JedI Knight and 1 for Mysteries of the Sith.

I copied all of the files on CD one and on the CD 2 i copied all of the videos Except CD 1 that i don't copy Res1Lo.Gob.

**Comment by shinyquagsire23** [comment]
I've ~tried to remove some file case issues (specifically, `resource/video/*.smk` will work fine) but it's still something I'm working on. My checklist would be:

- Make sure `openjkdf2-64` is being run from the same folder as `JK.EXE`.
- Make the `episode/` folder is all lowercase, not `Episode/` or `EPISODE/`
- Make sure `resource/` is all lowercase, not `Resource/` or `RESOURCE/`
- Make sure `resource/video/` is all lowercase
- In `episode/` and `resource/`, make sure all `.gob` files are lowercase extensions, not `.GOB` or `.Gob`
- Make sure `resource/shaders` contains the same files as `resource/shaders` in the repository

I think the long-term solution on my end will be to make a one-time installer on first startup that asks for a disk or GOG install and then it just copies and renames everything to `~/.local/openjkdf2`, definitely before any kind of 1.0.0 release. Definitely aware of how painful it is on Linux since that was where I first developed everything, lol

**Comment by darkstar252** [comment]
Ok i am not using .local/openjkdf2 i use $HOME/JK folder instead

**Comment by shinyquagsire23** [comment]
@darkstar252 Yeah I only just implemented `~/.local/share/openjkdf2/`. Just to be sure, what is the output of `tree .` or `ls .` where you're running from?

**Comment by darkstar252** [comment]
ok i have installed on :
$HOME/JK
and on 
$HOME/.local/share/openjkdf2

The same result as a consecuence. There is better to install on $HOME/jk or $HOME/games/jk not $HOME/.local/share because it's not good to install programs that are outside of linux on the directories part of the Linux tree.

**Comment by shinyquagsire23** [comment]
@darkstar252 The only possible issue is that you didn't rename files correctly. Can you run `tree $HOME/JK`?

**Comment by darkstar252** [comment]
   ~  tree $HOME/JK                                                                                                                                       127 ✘  19s  
/home/darkstar/JK
├── dbgcore.dll
├── dbghelp.dll
├── df2_reimpl.dll
├── df2_reimpl_kvm.dll
├── episode
│   ├── JK1CTF.gob
│   ├── JK1.gob
│   └── JK1MP.gob
├── exchndl.dll
├── glew32.dll
├── is_alive.txt
├── JK.EXE
├── libogg-0.dll
├── libvorbis-0.dll
├── libvorbisfile-3.dll
├── mgwhelp.dll
├── MUSIC
│   ├── Track12.ogg
│   ├── Track13.ogg
│   ├── Track14.ogg
│   ├── Track15.ogg
│   ├── Track16.ogg
│   ├── Track17.ogg
│   ├── Track18.ogg
│   ├── Track22.ogg
│   ├── Track23.ogg
│   ├── Track24.ogg
│   ├── Track25.ogg
│   ├── Track26.ogg
│   ├── Track27.ogg
│   ├── Track28.ogg
│   ├── Track29.ogg
│   ├── Track30.ogg
│   ├── Track31.ogg
│   └── Track32.ogg
├── OpenAL32.dll
├── openjkdf2-64
├── openjkdf2-64.exe
├── player
├── resource
│   ├── jk_.cd
│   ├── Res1hi.gob
│   ├── Res2.gob
│   ├── shaders
│   │   ├── default_f.glsl
│   │   ├── default_v.glsl
│   │   ├── menu_f.glsl
│   │   └── menu_v.glsl
│   └── video
│       ├── 01-02A.SMK
│       ├── 03-04A.SMK
│       ├── 06A.SMK
│       ├── 08-10A.SMK
│       ├── 12A.SMK
│       ├── 16A.SMK
│       ├── 18-19A.SMK
│       ├── 21A.SMK
│       ├── 23A.SMK
│       ├── 25A.SMK
│       ├── 27A.SMK
│       ├── 33-34A.SMK
│       ├── 36A.SMK
│       ├── 38A.SMK
│       ├── 39A.SMK
│       ├── 41-42A.SMK
│       ├── 41DA.SMK
│       ├── 41DSA.SMK
│       ├── 44A.SMK
│       ├── 46A.SMK
│       ├── 48A.SMK
│       ├── 50A.SMK
│       ├── 52-53A.SMK
│       ├── 54A.SMK
│       └── 57A.SMK
├── SDL2.dll
├── SDL2_mixer.dll
├── SMACKW32.DLL
├── symsrv.dll
└── symsrv.yes

6 directories, 73 files

**Comment by darkstar252** [comment]
In all of forms , thanks for the help :)

**Comment by shinyquagsire23** [comment]
@darkstar252 Hmmmm ok I'm kinda stumped now, can you pull the latest sources, rebuild, and copy the command line output? It should look something like:
```
Recreating SDL2 Window!
Loaded GOB file `resource/Res1hi.gob`...
Loaded GOB file `resource/Res2.gob`...
Premature 'END' found after only 787 lines in 'ui\jkstrings.uni'.  Check number in 'MSG xxx' header.
Premature 'END' found after only 25 lines in 'misc\sithStrings.uni'.  Check number in 'MSG xxx' header.
Using OpenAL+ALUT as audio backend
Premature 'END' found after only 187 lines in 'ui\cutStrings.uni'.  Check number in 'MSG xxx' header.
Premature 'END' found after only 451 lines in 'ui\credits.uni'.  Check number in 'MSG xxx' header.
stdMci: stop music
Opened file resource/video/01-02a.smk
Width: 640
Height: 300
Frames: 3446
FPS: 15.001500
OpenGL init...
Parse shader `resource/shaders/default_v.glsl`
Parse shader `resource/shaders/default_f.glsl`
Parse shader `resource/shaders/menu_v.glsl`
Parse shader `resource/shaders/menu_f.glsl`

...
```

**Comment by darkstar252** [comment]
I am not here at the computer at the night i rebuild the sources. Maybe there's the possibility of the cd-roms may contain diferentes binaries than the GOG release

**Comment by darkstar252** [comment]
If you want i can send you an ISO of the cd's

**Comment by darkstar252** [comment]
Possibly muy version of the Game is the Spanish language version but Will
see at night and prepare and send you the ISOS of the two cd's.

**Comment by shinyquagsire23** [comment]
I just tested with the GOG Spanish release and it works fine, but maybe the CD assets are compressed somehow? Maybe try downloading https://code.google.com/archive/p/starwarsjediknightaltinstall/ and use that to install the CD normally, then copy and rename the assets that way.

**Comment by darkstar252** [comment]
i recompile the game but i gave some error : 
En el fichero incluido desde src/Main/Main.c:41:
/home/darkstar/OpenJKDF2/src/Win95/Window.h:29:73: nota: se esperaba ‘WindowDrawHandler_t’ {también conocido como ‘int (*)(unsigned int)’} pero el argumento es de tipo ‘void (*)()’
   29 | void Window_SetDrawHandlers(WindowDrawHandler_t a1, WindowDrawHandler_t a2);
      |                                                     ~~~~~~~~~~~~~~~~~~~~^~
En el fichero incluido desde src/Main/Main.h:5,
                 desde src/Main/Main.c:1:
src/Main/Main.c: En la función ‘Main_Shutdown’:
/home/darkstar/OpenJKDF2/src/globals.h:2037:23: aviso: el paso del argumento 1 de ‘fclose’ crea un puntero desde un entero sin una conversión [-Wint-conversion]
 2037 | #define debug_log_fp (*(stdFile_t *)debug_log_fp_ADDR)
      |                      ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                       |
      |                       stdFile_t {también conocido como int}
src/Main/Main.c:332:16: nota: en expansión de macro ‘debug_log_fp’
  332 |         fclose(debug_log_fp);
      |                ^~~~~~~~~~~~
En el fichero incluido desde src/Main/../jk.h:5,
                 desde src/Main/Main.c:3:
/usr/i686-w64-mingw32/include/stdio.h:611:28: nota: se esperaba ‘FILE *’ {también conocido como ‘struct _iobuf *’} pero el argumento es de tipo ‘stdFile_t’ {también conocido como ‘int’}
  611 |   int __cdecl fclose(FILE *_File);
      |                      ~~~~~~^~~~~
make: *** [Makefile:22: build/Main/Main.o] Error 1

Using the build.sh script from the folder .

And i recompile in x86_64 before that no errors i try....

**Comment by darkstar252** [comment]
Ok message : 

    ~/JK  ./openjkdf2                                                                                                                                                  ✔ 
Recreating SDL2 Window!
FATAL ERROR: ERR_CANNOT_LOAD_FILE ui\sft\small0.sft

**Comment by darkstar252** [comment]
how to send you the isos of the game for pure testing and reverse engeniering

**Comment by darkstar252** [comment]
Ok i think it's extracting and this seems like there is a compressed file with no compressed extension like .zip or other what that hell!!! Ohhh . i install and copy viewing the readme instructions thanks for the help if something is wrong.. i will tell you

**Comment by darkstar252** [comment]
Ok thank you very much, that was the problem now the game runs :) Question preferences for the full screen loading instead of Window?

**Comment by shinyquagsire23** [comment]
@darkstar252 currently I don't have fullscreen implemented, I'll see if I can add an option for that. The window is resizable without any issues though, and I think maximizing works as well.

**Comment by darkstar252** [comment]
> @darkstar252 currently I don't have fullscreen implemented, I'll see if I can add an option for that. The window is resizable without any issues though, and I think maximizing works as well.

The original game launches in full screen automatically. I don't think it's very urgent, but it's very reasonable to have full screen.
