### ISSUE TITLE
Game Breaking Bug: Door Button Doesn't Work

### ISSUE THREAD

**Issue by shmabler** [shinyquagsire23/OpenJKDF2#315]
On level 3 the circle switch/button on the wall does not work. You cannot progress in the game without this button working.

The button can be seen working in this video at time index 13:52, but in OpenJKDF2 it does not respond to pressing space bar to activate the button and nothing happens.

Star Wars Jedi Knight: Dark Forces II - PC - Level 3 - The Return Home to Sulon (Blind, Hard Diff)
https://youtu.be/icVz1ttYsq0?feature=shared&t=832

**Comment by MarcoWanke** [comment]
This might be a stupid question but have you collected the red key? You need it to activate this switch. For me the switch is working every time in OpenJKDF2.

**Comment by shmabler** [comment]
> This might be a stupid question but have you collected the red key? You need it to activate this switch. For me the switch is working every time in OpenJKDF2.

I didn't even realize that was a key button. I thought I had been everywhere. It would have been nice if there was some message on screen for need the key like in Quake. I guess I'm used to that. I found the red key and the door opens, thanks.

Just a thought though, could the OpenJKDF2 somehow add an onscreen message to say you need the (color) key when  you press space bar, similarly to Quake or Doom?

**Comment by shmabler** [comment]
issue closed

**Comment by MarcoWanke** [comment]
> > This might be a stupid question but have you collected the red key? You need it to activate this switch. For me the switch is working every time in OpenJKDF2.
> 
> I didn't even realize that was a key button. I thought I had been everywhere. It would have been nice if there was some message on screen for need the key like in Quake. I guess I'm used to that. I found the red key and the door opens, thanks.
> 
> Just a thought though, could the OpenJKDF2 somehow add an onscreen message to say you need the (color) key when you press space bar, similarly to Quake or Doom?
> 
> It does that for locked doors (that never open, open later?) but only the first time, after that it will make a click sound. A message every time for that might also be useful.
> 
> Oh, and somewhere that lists what items like keys or yellow wrench you have etc. would be nice.

Unfortunately the game doesn’t tells you that directly. The only indication is the red circle so you need a red key. Like the spots for the yellow and blue wrenches.

**Comment by MarcoWanke** [comment]
> Oh, and somewhere that lists what items like keys or yellow wrench you have etc. would be nice.

You  can see what items you have when you scroll through your inventory by pressing the next or previous item key. 

![IMG_3084](https://github.com/shinyquagsire23/OpenJKDF2/assets/137448969/6571007d-98e4-49f0-84cd-469e9e8fe848)
