### ISSUE TITLE
crash when trying to open map

### ISSUE THREAD

**Issue by farmboy0** [shinyquagsire23/OpenJKDF2#33]
#0  0x0000000000415c50 in ?? ()
#1  0x000000000061d1d6 in jkGuiEsc_Show () at src/Gui/jkGUIEsc.c:113
#2  0x00000000006567c6 in jkMain_GuiAdvance () at src/Main/jkMain.c:176
#3  0x00000000006b63d0 in Window_Main_Loop () at src/Win95/Window.c:756
#4  Window_Main_Linux (argc=<optimized out>, argv=<optimized out>) at src/Win95/Window.c:843
#5  0x00000000004fc75b in main (argc=1, argv=0x7fffffffd288) at src/main.c:345

**Comment by shinyquagsire23** [comment]
Fixed I forget which release
