### ISSUE TITLE
crash when entering keyboard menu

### ISSUE THREAD

**Issue by farmboy0** [shinyquagsire23/OpenJKDF2#34]
#0  0x0000000000412830 in ?? ()
#1  0x0000000000634b95 in jkGuiSetup_Show () at src/Gui/jkGUISetup.c:121
#2  0x000000000061d2af in jkGuiEsc_Show () at src/Gui/jkGUIEsc.c:151
#3  0x00000000006567c6 in jkMain_GuiAdvance () at src/Main/jkMain.c:176
#4  0x00000000006b63d0 in Window_Main_Loop () at src/Win95/Window.c:756
#5  Window_Main_Linux (argc=<optimized out>, argv=<optimized out>) at src/Win95/Window.c:843
#6  0x00000000004fc75b in main (argc=1, argv=0x7fffffffd288) at src/main.c:345

**Comment by farmboy0** [comment]
Sorry, just realized that the crashes I reported are included in the list of unimplemented features. If you could implement this one at least that would be great. Currently I can only move sideways and i dont really know how to edit the bindings in the config file(is there are description of that?).

**Comment by shinyquagsire23** [comment]
Implemented v0.1.19

**Comment by farmboy0** [comment]
Thank you
