### ISSUE TITLE
release windows version

### ISSUE THREAD

**Issue by ghost** [shinyquagsire23/OpenJKDF2#348]
Hi

Is it possible to release a compiled windows version for people not knowing how to compile it?

**Comment by shinyquagsire23** [comment]
There's binaries at https://github.com/shinyquagsire23/OpenJKDF2/releases, they're at the bottom of the version post

**Comment by shinyquagsire23** [comment]
ok got all the build issues sorted out, v0.9.2 should fix the map select crash issue at least

**Comment by starwars-girl** [comment]
Thanks!

**Comment by starwars-girl** [comment]
why is not a release version there?

**Comment by shinyquagsire23** [comment]
It's just debug for now so I can collect crash issues
