### ISSUE TITLE
Gamma correction is missing

### ISSUE THREAD

**Issue by shinyquagsire23** [shinyquagsire23/OpenJKDF2#37]
Running in WINE, JK.EXE seems to have a brighter gamma curve than OpenJKDF2. Probably a good idea to add an adjustment slider to the display options.

**Comment by Alex3474247** [comment]
Yes, this is an important issue and I felt it strongly at 17th level.

**Comment by shinyquagsire23** [comment]
cc @Alex3474247 

Fixed v0.3.12
