### ISSUE TITLE
Crash on force power screen after MAW

### ISSUE THREAD

**Issue by OCircles** [shinyquagsire23/OpenJKDF2#39]
The star removing thing is borked

-------

Error occurred on Wednesday, December 15, 2021 at 17:49:47.

openjkdf2-64.exe caused an Access Violation at location 00000000004C94C0 DEP violation at location 00000000004C94C0.

AddrPC           Params
00000000004C94C0 00007FF7076462D0 00000003073EA460 0000008C149FF020
00007FF70736BF54 00007FF7073EA4E0 00007FF7074093C2 00007FF7074093B7  openjkdf2-64.exe!jkGuiForce_ChoiceRemoveStars
00007FF707372917 00007FF7073EA4E0 00007FF7073EA0E0 00007FF7074093B7  openjkdf2-64.exe!jkGuiRend_DisplayAndReturnClicked
00007FF70736C8E1 0000008C00000000 00007FF700000000 0000008C00000001  openjkdf2-64.exe!jkGuiForce_Show
00007FF70738770B 000000000000000B 00007FF700000007 0000000000000000  openjkdf2-64.exe!jkMain_ChoiceShow
00007FF707386A12 0000000000000000 00007FF90000000F 0000000000000000  openjkdf2-64.exe!jkMain_GuiAdvance
00007FF70739FD25 0000000000000000 0000008C0000000F 0000000000000000  openjkdf2-64.exe!Window_Main_Loop
00007FF70739FF6E 000001A200000001 000001A2A6D1C390 000001A2A6CD0030  openjkdf2-64.exe!Window_Main_Linux
00007FF7072F2C92 0000000000000001 000001A2A6D1C390 0000000000000029  openjkdf2-64.exe!SDL_main
00007FF7073D2D41 0000000000000000 000000000000002A 00007FF70770AF98  openjkdf2-64.exe!main_getcmdline  [/Users/valve/release/SDL/SDL2-2.0.16-source/foo-x64/../src/main/windows/SDL_windows_main.c @ 82]
00007FF7072F13C1 0000000000000000 0000000000000000 0000000000000000  openjkdf2-64.exe!__tmainCRTStartup
00007FF7072F14D6 0000000000000000 0000000000000000 0000000000000000  openjkdf2-64.exe!WinMainCRTStartup
00007FF953337034 0000000000000000 0000000000000000 0000000000000000  KERNEL32.DLL!BaseThreadInitThunk
00007FF953BC2651 0000000000000000 0000000000000000 0000000000000000  ntdll.dll!RtlUserThreadStart

openjkdf2-64.exe
ntdll.dll   	6.2.19041.1288
KERNEL32.DLL	6.2.19041.1348
KERNELBASE.dll	6.2.19041.1348
ADVAPI32.dll	6.2.19041.1052
msvcrt.dll  	7.0.19041.546
sechost.dll 	6.2.19041.906
RPCRT4.dll  	6.2.19041.1288
SHELL32.dll 	6.2.19041.1320
msvcp_win.dll	6.2.19041.789
ucrtbase.dll	6.2.19041.789
USER32.dll  	6.2.19041.1202
OPENGL32.dll	6.2.19041.1081
win32u.dll  	6.2.19041.1320
combase.dll 	6.2.19041.1348
GDI32.dll   	6.2.19041.1202
gdi32full.dll	6.2.19041.1110
GLU32.dll   	6.2.19041.1081
exchndl.dll 	0.9.3.0
glew32.dll  	2.1.0.0
OpenAL32.dll	1.21.1.0
PSAPI.DLL   	6.2.19041.546
ole32.dll   	6.2.19041.1202
SDL2.dll    	2.0.16.0
SDL2_mixer.dll	2.0.4.0
IMM32.dll   	6.2.19041.546
mgwhelp.dll 	0.9.3.0
OLEAUT32.dll	6.2.19041.985
VERSION.dll 	6.2.19041.546
SETUPAPI.dll	6.2.19041.1237
WINMM.dll   	6.2.19041.546
cfgmgr32.dll	6.2.19041.1151
dbghelp.dll 	10.0.19041.685
bcrypt.dll  	6.2.19041.1023
dbgcore.DLL 	10.0.19041.685
shcore.dll  	6.2.19041.1320
uxtheme.dll 	6.2.19041.1266
IconCodecService.dll	6.2.19041.1
WindowsCodecs.dll	6.2.19041.1151
kernel.appcore.dll	6.2.19041.546
bcryptPrimitives.dll	6.2.19041.1348
clbcatq.dll 	2001.12.10941.16384
MMDevApi.dll	6.2.19041.1023
DEVOBJ.dll  	6.2.19041.1151
avrt.dll    	6.2.19041.546
MSCTF.dll   	6.2.19041.1202
AppXDeploymentClient.dll	6.2.19041.1288
nvoglv64.dll	27.21.14.5671
WTSAPI32.dll	6.2.19041.546
msasn1.dll  	6.2.19041.546
cryptnet.dll	6.2.19041.906
CRYPT32.dll 	6.2.19041.1320
cryptbase.dll	6.2.19041.546
WINTRUST.dll	6.2.19041.1266
ntmarta.dll 	6.2.19041.546
dxcore.dll  	6.2.19041.546
windows.storage.dll	6.2.19041.1320
Wldp.dll    	6.2.19041.1320
shlwapi.dll 	6.2.19041.1023
dwmapi.dll  	6.2.19041.746
powrprof.dll	6.2.19041.546
UMPDC.dll
WINSTA.dll  	6.2.19041.546
textinputframework.dll	6.2.19041.1320
CoreMessaging.dll	6.2.19041.746
CoreUIComponents.dll	6.2.19041.546
WS2_32.dll  	6.2.19041.546
wintypes.dll	6.2.19041.1348
AUDIOSES.DLL	6.2.19041.1023
resourcepolicyclient.dll	6.2.19041.546
symsrv.dll  	10.0.19041.685
wininet.dll 	11.0.19041.1320
iertutil.dll	11.0.19041.1266
SspiCli.dll 	6.2.19041.1266
profapi.dll 	6.2.19041.844
ondemandconnroutehelper.dll	6.2.19041.546
winhttp.dll 	6.2.19041.1320
mswsock.dll 	6.2.19041.546
IPHLPAPI.DLL	6.2.19041.546
NSI.dll     	6.2.19041.610
WINNSI.DLL  	6.2.19041.546
urlmon.dll  	11.0.19041.1320
srvcli.dll  	6.2.19041.546
netutils.dll	6.2.19041.546
DNSAPI.dll  	6.2.19041.1320
rasadhlp.dll	6.2.19041.546
fwpuclnt.dll	6.2.19041.1348

Windows 6.2.9200
DrMingw 0.9.3

**Comment by shinyquagsire23** [comment]
Fixed 401d30baf2823dd3a5911bc595525136a0a53bfa

**Comment by shinyquagsire23** [comment]
Resolved w/ v0.2.3
