### ISSUE TITLE
Re-use code from the gorc engine?

### ISSUE THREAD

**Issue by neuromancer** [shinyquagsire23/OpenJKDF2#4]
[Gorc](https://github.com/jdmclark/gorc) is an early-development Dark Forces II game engine recreation. It goal is to replace the original game executable, allowing the original singleplayer and multiplayer levels to be played on new platforms. It could be useful to re-use some of its code for OpenJKDF2.

**Comment by shinyquagsire23** [comment]
2 years late but just wanted to clear out some issues, atm I don't have any plans to borrow from Gorc (actually committed some UI stuff to it a while back), but I will admit I looked at it for documentation on a few file formats which were hard to find information on.

**Comment by neuromancer** [comment]
Thanks for the clarification (I'm following this, even after years)
