### ISSUE TITLE
Surfaces don't get hit by explosions

### ISSUE THREAD

**Issue by OCircles** [shinyquagsire23/OpenJKDF2#40]
Seems to be the case for all the surfaces that are supposed to be triggered by an explosion/conc. They're supposed to break when shot in just the general vicinity

https://streamable.com/qzkttn

**Comment by shinyquagsire23** [comment]
Fixed 862e5112f31b39f0b11fa0af81e1dec430c5f023

**Comment by shinyquagsire23** [comment]
Implemented v0.2.10
