### ISSUE TITLE
Force Jump in 3rd person cam causes certain things to switch render mode

### ISSUE THREAD

**Issue by OCircles** [shinyquagsire23/OpenJKDF2#42]
https://streamable.com/bcc9e2

Also happened in Pic and Gork fight while Pic was invisible, I guess it's related to some generic force power effect?

Happens to Gonks but not Stormtroopers..?

I also saw it happen with a breakable surface but I'm not sure if they just cheated and used a Thing for that specific one instead?

**Comment by shinyquagsire23** [comment]
Fixed 49aef8f60fd9e3ffeff08ad104ff6f494dab40c0, I had a bug in rdSprite which changed the global render modes.

**Comment by shinyquagsire23** [comment]
Resolved w/ v0.2.3
