### ISSUE TITLE
2nd Yun fight intro camera doesn't play

### ISSUE THREAD

**Issue by OCircles** [shinyquagsire23/OpenJKDF2#43]
Should be mentioned that the beginning of this camera movement in the original game is kinda glitchy so maybe it's something to do with that. Had no problems with any of the other ones throughout.

**Comment by shinyquagsire23** [comment]
Fixed cc6bc63138a4bc0c2cc3b871113ae784c409128e

**Comment by shinyquagsire23** [comment]
Implemented v0.2.11
