### ISSUE TITLE
The inside of Things gets rendered when camera clips

### ISSUE THREAD

**Issue by OCircles** [shinyquagsire23/OpenJKDF2#44]
https://streamable.com/ens8lw

Makes this specific trick fall really difficult, but also lets you see a really creepy inverted Kyle face when you're crouched in a tight area

**Comment by shinyquagsire23** [comment]
Huh, I didn't know the game did backface culling but I guessss it makes sense that a longer near-clipping plane + backface cull = no rendering, maybe.

**Comment by shinyquagsire23** [comment]
Fixed b605ef1c3dbeadac42487111700ee2c025530681

**Comment by shinyquagsire23** [comment]
Implemented v0.2.6

**Comment by shinyquagsire23** [comment]
OK so JKDF2 definitely doesn't use backface culling, instead it seems like somehow the camera/thing sphere clipping is screwing up. Might be related to #40

**Comment by shinyquagsire23** [comment]
fixed by implementing backface culling correctly this time, v0.2.9
