### ISSUE TITLE
Quicksave sets Kyle's animation to default pose

### ISSUE THREAD

**Issue by OCircles** [shinyquagsire23/OpenJKDF2#45]
https://streamable.com/z148se

There was another issue I had regarding loading a save with a cooked TD and not having Kyle's animation be the one where he's cooking the TD, but I think it's actually caused by this quicksave issue

**Comment by shinyquagsire23** [comment]
Semi-fixed 7fc54093459c65dde8725aba3a7b487ab1f8b7ae, loading will still briefly have a default pose though.

**Comment by shinyquagsire23** [comment]
Semi-resolved w/ v0.2.3

**Comment by shinyquagsire23** [comment]
Fixed properly (e770d2f7fce851f7175f8ba4fb078aa3cb2e1c17), set for next release

**Comment by shinyquagsire23** [comment]
Fixed v0.6.12
