### ISSUE TITLE
Game becomes unstable if using 'space' to pause cutscenes

### ISSUE THREAD

**Issue by scotsdez** [shinyquagsire23/OpenJKDF2#48]
When any of the cutscenes are playing (including the LucasArts logo), pressing space, which normally pauses cutscenes, makes the game unresponsive. The audio from the video file will continue to play, but the screen freezes and becomes unresponsive in Windows, and must be force closed (the ultimate dark side power).

**Comment by shinyquagsire23** [comment]
Fixed 49aef8f60fd9e3ffeff08ad104ff6f494dab40c0

**Comment by shinyquagsire23** [comment]
Resolved w/ v0.2.3
