### ISSUE TITLE
Mac build won't run without installing several dependencies through Homebrew

### ISSUE THREAD

**Issue by CelestialAmber** [shinyquagsire23/OpenJKDF2#49]
I tried running the Mac build on Monterey, but it wouldn't run until I installed several libraries in Homebrew, including libogg, among others. Even then, it still crashed with I think a EXEC_BAD_ACCESS error or something.

**Comment by shinyquagsire23** [comment]
Hmmmm I thought I'd managed to fix that, but libSDL2_mixer had dependencies I hadn't fixed up

**Comment by shinyquagsire23** [comment]
Should be fixed in v0.2.4

**Comment by shinyquagsire23** [comment]
Actually wait do you have a crash log for the EXEC_BAD_ACCESS error?

**Comment by CelestialAmber** [comment]
Sorry, it was actually a EXC_BAD_INSTRUCTION error. Here is the crash log.
[crashlog.txt](https://github.com/shinyquagsire23/OpenJKDF2/files/7738771/crashlog.txt)

**Comment by shinyquagsire23** [comment]
Oh, I think it's failing to find your game data (and then it crashed when showing an error about that). You'll need a copy of the original game data at `~/.local/share/openjkdf2`, or in the same folder as the `.app` (at some point I'll add an actual installer or something).

**Comment by CelestialAmber** [comment]
I swear it gave the same error even with the game data, but I didn't have all the files, so I'll retry and see what happens.

**Comment by CelestialAmber** [comment]
Even with the assets present it still gives the same error. I tried manually executing the executable file in Terminal, and it works.

**Comment by shinyquagsire23** [comment]
I ended up implementing the installer as of v0.2.7. If you have a GOG installation or original CDs/images, it can now do a one-time install of all the assets (as well as list out any assets which are required but missing). Should make macOS installation a bit more straightforward I think.
