### ISSUE TITLE
Error compiling on manjaro..

### ISSUE THREAD

**Issue by darkstar252** [shinyquagsire23/OpenJKDF2#5]
[darkstar@WOPR OpenJKDF2]$ qmake openjkdf2.pro && make && ./openjkdf2 JK.EXE
WARNING: Failure to find: renderer.h
g++ -c -pipe -g -Wno-unused-parameter -Wall -Wextra -D_REENTRANT -fPIC -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/qt -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtCore -I. -I/usr/lib/qt/mkspecs/linux-g++ -o main.o main.cpp
En el fichero incluido desde main.cpp:23:
dlls/ddraw/IDirectDraw4.h:10:10: error fatal: renderer.h: No existe el fichero o el directorio (No such file or directory)
   10 | #include "renderer.h"
      |          ^~~~~~~~~~~~
compilación terminada. (compilaton finished.)
make: *** [Makefile:1391: main.o] Error 1
[darkstar@WOPR OpenJKDF2]$

**Comment by shinyquagsire23** [comment]
I think I committed this file a while back, let me know if you still get build errors though, haven't tested on many machines.

**Comment by SMLiberator** [comment]
I'm missing unicorn.h. Is it supposed to be obtained from elsewhere?

g++ -c -m64 -pipe -g -Wno-unused-parameter -fpermissive -Wall -W -D_REENTRANT -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -o build/main.o main.cpp
In file included from main.cpp:1:0:
main.h:4:10: fatal error: unicorn/unicorn.h: No such file or directory
 #include <unicorn/unicorn.h>
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:651: recipe for target 'build/main.o' failed
make: *** [build/main.o] Error 1

**Comment by orderorder** [comment]
Use `sudo pacman -S unicorn` to install the required files
