### ISSUE TITLE
Crash on removing player profile

### ISSUE THREAD

**Issue by OCircles** [shinyquagsire23/OpenJKDF2#50]
https://i.imgur.com/h7wKAjw.jpeg

This button is deadly

-------------------

Error occurred on Saturday, December 18, 2021 at 04:04:01.

openjkdf2-64.exe caused an Access Violation at location 0000000000431C20 DEP violation at location 0000000000431C20.

AddrPC           Params
0000000000431C20 000000F6D75FEF20 000000F600000080 00007FF67AE291AB
00007FF67AD91E2D 000002F300000001 0000000000000000 000002F3FAC15600  openjkdf2-64.exe!jkGuiPlayer_ShowNewPlayer
00007FF67AD8E4FF 00007FF600000000 00007FF67B08F944 000000000000007F  openjkdf2-64.exe!jkGuiMain_Show
00007FF67ADA7683 0000000000000003 00007FF600000002 0000000000000000  openjkdf2-64.exe!jkMain_MainShow
00007FF67ADA69E2 0000000000000000 00007FF90000000F 0000000000000000  openjkdf2-64.exe!jkMain_GuiAdvance
00007FF67ADBFCE5 0000000000000000 000000F60000000F 0000000000000000  openjkdf2-64.exe!Window_Main_Loop
00007FF67ADBFF2E 000002F300000001 000002F3FAC3A090 000002F3FAF80030  openjkdf2-64.exe!Window_Main_Linux
00007FF67AD12C92 0000000000000001 000002F3FAC3A090 0000000000000029  openjkdf2-64.exe!SDL_main
00007FF67ADF2DA1 0000000000000000 000000000000002A 00007FF67B129F98  openjkdf2-64.exe!main_getcmdline  [/Users/valve/release/SDL/SDL2-2.0.16-source/foo-x64/../src/main/windows/SDL_windows_main.c @ 82]
00007FF67AD113C1 0000000000000000 0000000000000000 0000000000000000  openjkdf2-64.exe!__tmainCRTStartup
00007FF67AD114D6 0000000000000000 0000000000000000 0000000000000000  openjkdf2-64.exe!WinMainCRTStartup
00007FF953337034 0000000000000000 0000000000000000 0000000000000000  KERNEL32.DLL!BaseThreadInitThunk
00007FF953BC2651 0000000000000000 0000000000000000 0000000000000000  ntdll.dll!RtlUserThreadStart

openjkdf2-64.exe
ntdll.dll   	6.2.19041.1288
KERNEL32.DLL	6.2.19041.1348
KERNELBASE.dll	6.2.19041.1348
ADVAPI32.dll	6.2.19041.1052
msvcrt.dll  	7.0.19041.546
sechost.dll 	6.2.19041.906
RPCRT4.dll  	6.2.19041.1288
SHELL32.dll 	6.2.19041.1320
msvcp_win.dll	6.2.19041.789
ucrtbase.dll	6.2.19041.789
USER32.dll  	6.2.19041.1202
OPENGL32.dll	6.2.19041.1081
win32u.dll  	6.2.19041.1320
GDI32.dll   	6.2.19041.1202
combase.dll 	6.2.19041.1348
gdi32full.dll	6.2.19041.1110
GLU32.dll   	6.2.19041.1081
exchndl.dll 	0.9.3.0
OpenAL32.dll	1.21.1.0
glew32.dll  	2.1.0.0
PSAPI.DLL   	6.2.19041.546
SDL2.dll    	2.0.16.0
ole32.dll   	6.2.19041.1202
IMM32.dll   	6.2.19041.546
SDL2_mixer.dll	2.0.4.0
OLEAUT32.dll	6.2.19041.985
SETUPAPI.dll	6.2.19041.1237
mgwhelp.dll 	0.9.3.0
VERSION.dll 	6.2.19041.546
cfgmgr32.dll	6.2.19041.1151
bcrypt.dll  	6.2.19041.1023
WINMM.dll   	6.2.19041.546
dbghelp.dll 	10.0.19041.685
dbgcore.DLL 	10.0.19041.685
shcore.dll  	6.2.19041.1320
uxtheme.dll 	6.2.19041.1266
IconCodecService.dll	6.2.19041.1
WindowsCodecs.dll	6.2.19041.1151
kernel.appcore.dll	6.2.19041.546
bcryptPrimitives.dll	6.2.19041.1348
clbcatq.dll 	2001.12.10941.16384
MMDevApi.dll	6.2.19041.1023
DEVOBJ.dll  	6.2.19041.1151
avrt.dll    	6.2.19041.546
MSCTF.dll   	6.2.19041.1202
AppXDeploymentClient.dll	6.2.19041.1288
nvoglv64.dll	27.21.14.5671
WTSAPI32.dll	6.2.19041.546
msasn1.dll  	6.2.19041.546
cryptnet.dll	6.2.19041.906
CRYPT32.dll 	6.2.19041.1320
cryptbase.dll	6.2.19041.546
WINTRUST.dll	6.2.19041.1266
ntmarta.dll 	6.2.19041.546
dxcore.dll  	6.2.19041.546
windows.storage.dll	6.2.19041.1320
Wldp.dll    	6.2.19041.1320
shlwapi.dll 	6.2.19041.1023
dwmapi.dll  	6.2.19041.746
powrprof.dll	6.2.19041.546
UMPDC.dll
WINSTA.dll  	6.2.19041.546
textinputframework.dll	6.2.19041.1320
CoreMessaging.dll	6.2.19041.746
CoreUIComponents.dll	6.2.19041.546
WS2_32.dll  	6.2.19041.546
wintypes.dll	6.2.19041.1348
AUDIOSES.DLL	6.2.19041.1023
resourcepolicyclient.dll	6.2.19041.546
symsrv.dll  	10.0.19041.685
wininet.dll 	11.0.19041.1320
iertutil.dll	11.0.19041.1266
SspiCli.dll 	6.2.19041.1266
profapi.dll 	6.2.19041.844
ondemandconnroutehelper.dll	6.2.19041.546
winhttp.dll 	6.2.19041.1320
mswsock.dll 	6.2.19041.546
IPHLPAPI.DLL	6.2.19041.546
NSI.dll     	6.2.19041.610
WINNSI.DLL  	6.2.19041.546
urlmon.dll  	11.0.19041.1320
srvcli.dll  	6.2.19041.546
netutils.dll	6.2.19041.546
DNSAPI.dll  	6.2.19041.1320
rasadhlp.dll	6.2.19041.546
fwpuclnt.dll	6.2.19041.1348

Windows 6.2.9200
DrMingw 0.9.3

**Comment by shinyquagsire23** [comment]
Fixed 26b2a04bc840bd3c9529adba0d05725a14abf0c4

**Comment by shinyquagsire23** [comment]
Implemented v0.2.6
