### ISSUE TITLE
Saving makes broken saves, loading them breaks the game until restart

### ISSUE THREAD

**Issue by solek1312** [shinyquagsire23/OpenJKDF2#54]
If you launch new game it's fine, you can play, do quicksaves, do it again in all combinations.
But as soon as you load a save made in openjkdf2, something in the game breaks until next restart.
If you load a save all weapons stop working (shooting, switching, picking up ammo, etc).
If you try to shoot a gun, it releases some shot particles, plays a weapon animation, and the message on top says "COG_00000".

If you launch a new game after that, the first time you can't move at all.
The second time and onward shooting a gun makes it twitch but do nothing and switching gets messed up too.
It happens with all saves made using openjkdf2.
Loading saves made in native JK doesn't break anything, they work great just as launching a clean new game.
AI and other things work as intended even in broken saves.

Built for Ubuntu 20.04.

**Comment by shinyquagsire23** [comment]
I thiiiink this should be fixed with 9d0a50e3d512abb8e130037cdc0f092bfd014d44

**Comment by shinyquagsire23** [comment]
Didn't really break between v0.2.10 and v0.2.11, but the v0.2.11 should be the next stable tag for Ubuntu
