### ISSUE TITLE
Saves don't work on Windows 10 64bit v1909, assertion failed

### ISSUE THREAD

**Issue by Alex3474247** [shinyquagsire23/OpenJKDF2#56]
The engine is compiled from the latest sources(v0.2.12), cmake 3.22, MSVC 2019 Community, python 3.10.
Here is some technical information about the problem:
Debug Assertion Failed!

Program: C:\Users\User\Documents\Openjkdf2\build\Debug\openjkdf2-64.exe
File: minkernel\crts\ucrt\src\appcrt\convert\isctype.cpp
Line: 36 or 42

Expression: c >= -1 && c <= 255

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts.

(Press Retry to debug the application)
If I press retry, a breakpoint toggled in jk.c, line 986
Trying to save game:
 	ucrtbased.dll!00007ffae32a5c8a()	Unknown
 	ucrtbased.dll!00007ffae32a5c17()	Unknown
 	ucrtbased.dll!00007ffae32af619()	Unknown
 	ucrtbased.dll!00007ffae32afeb3()	Unknown
>	openjkdf2-64.exe!_iswspace(int a) Line 986	
 	openjkdf2-64.exe!stdFont_sub_4352C0(wchar_t * a1, stdFont * a2, int a3, rdRect * a4, int * a5) Line 716	
 	openjkdf2-64.exe!stdFont_Draw2(stdVBuffer * a1, stdFont * a2, unsigned int a3, int a4, rdRect * a5, wchar_t * a6, int a7) Line 281	
 	openjkdf2-64.exe!stdFont_Draw3(stdVBuffer * paintSurface, stdFont * font, int a3, rdRect * a4, int a5, wchar_t * a6, int a7) Line 594	
 	openjkdf2-64.exe!jkGuiRend_TextDraw(jkGuiElement * element, jkGuiMenu * menu, stdVBuffer * outBuf, int redraw) Line 2194	
 	openjkdf2-64.exe!jkGuiRend_UpdateAndDrawClickable(jkGuiElement * clickable, jkGuiMenu * menu, int forceRedraw) Line 724	
 	openjkdf2-64.exe!jkGuiRend_ClickableMouseover(jkGuiMenu * menu, jkGuiElement * element) Line 934	
 	openjkdf2-64.exe!jkGuiRend_MouseMovedCallback(jkGuiMenu * menu, int x, int y) Line 983	
 	openjkdf2-64.exe!jkGuiRend_UpdateMouse(...) Line 1608	
 	openjkdf2-64.exe!jkGuiRend_sub_50FAD0(jkGuiMenu * menu) Line 375	
 	openjkdf2-64.exe!jkGuiRend_gui_sets_handler_framebufs(jkGuiMenu * menu) Line 382	
 	openjkdf2-64.exe!jkGuiRend_DisplayAndReturnClicked(jkGuiMenu * menu) Line 281	
 	openjkdf2-64.exe!jkGuiSaveLoad_Show(int bIsSave) Line 320	
 	openjkdf2-64.exe!jkGuiEsc_Show(...) Line 140	
 	openjkdf2-64.exe!jkMain_EscapeMenuShow(int a1, int a2) Line 194	
 	openjkdf2-64.exe!jkMain_GuiAdvance(...) Line 177	
 	openjkdf2-64.exe!Window_Main_Loop(...) Line 815	
 	openjkdf2-64.exe!Window_Main_Linux(int argc, char * * argv) Line 903	
 	openjkdf2-64.exe!main(int argc, char * * argv) Line 183	
 	[External Code]	

Reassign the game controls(fire key for example):
 	ucrtbased.dll!00007ffadffb5c04()	Unknown
 	ucrtbased.dll!00007ffadffbf619()	Unknown
 	ucrtbased.dll!00007ffadffbfeb3()	Unknown
>	openjkdf2-64.exe!_iswspace(int a) Line 986	C=
 	openjkdf2-64.exe!stdFont_sub_4352C0(wchar_t * a1, stdFont * a2, int a3, rdRect * a4, int * a5) Line 716	C=
 	openjkdf2-64.exe!stdFont_Draw3(stdVBuffer * paintSurface, stdFont * font, int a3, rdRect * a4, int a5, wchar_t * a6, int a7) Line 416	
 	openjkdf2-64.exe!jkGuiRend_TextDraw(jkGuiElement * element, jkGuiMenu * menu, stdVBuffer * outBuf, int redraw) Line 2194	
 	openjkdf2-64.exe!jkGuiRend_UpdateAndDrawClickable(jkGuiElement * clickable, jkGuiMenu * menu, int forceRedraw) Line 724	
 	openjkdf2-64.exe!jkGuiRend_Paint(jkGuiMenu * menu) Line 241	
 	openjkdf2-64.exe!jkGuiRend_gui_sets_handler_framebufs(jkGuiMenu * menu) Line 391	
 	openjkdf2-64.exe!jkGuiRend_DisplayAndReturnClicked(jkGuiMenu * menu) Line 281	
 	openjkdf2-64.exe!jkGuiDialog_YesNoDialog(wchar_t * stringA, wchar_t * stringB) Line 131	
 	openjkdf2-64.exe!jkGuiKeyboard_sub_4123C0(jkGuiMenu * pMenu) Line 408	
 	openjkdf2-64.exe!jkGuiRend_DisplayAndReturnClicked(jkGuiMenu * menu) Line 301	
 	openjkdf2-64.exe!jkGuiKeyboard_Show(...) Line 545	
 	openjkdf2-64.exe!jkGuiSetup_Show(...) Line 121	
 	openjkdf2-64.exe!jkGuiEsc_Show(...) Line 150	
 	openjkdf2-64.exe!jkMain_EscapeMenuShow(int a1, int a2) Line 194	
 	openjkdf2-64.exe!jkMain_GuiAdvance(...) Line 177	
 	openjkdf2-64.exe!Window_Main_Loop(...) Line 815	
 	openjkdf2-64.exe!Window_Main_Linux(int argc, char * * argv) Line 903	
 	openjkdf2-64.exe!main(int argc, char * * argv) Line 183	
 	[External Code]	
Quicksave by F9 works but you still cannot use your quicksave, an error occurs as above.

**Comment by shinyquagsire23** [comment]
Fixed 555bf65ee414a13c5cdf908c584c5c6b93b1bef4
