### ISSUE TITLE
Music (Not) Repeating

### ISSUE THREAD

**Issue by bangstk** [shinyquagsire23/OpenJKDF2#6]
Hello;

This is a bug in the original game but it's some strange behavior that can probably now be figured out with the reverse engineering project:

It is commonly reported that the music in Jedi Knight doesn't repeat after the tracks have finished, but what I have discovered is that it does repeat under a peculiar circumstance: the music will restart only if the player stands still and touches no controls for about 2 seconds.

**Comment by shinyquagsire23** [comment]
hmmmm I know GOG uses some MCI replacement which apparently is kinda buggy, I haven't noticed anything indicating this bug might happen on an actual CD though, the MCI dll APIs are fairly straightforward. I think long-term though I do want to have an in-built OGG replacement for all the MCI stuff, I have a shim in the KVM stuff but I'd have to port it to its own DLL...

In any case I'll leave this issue open to track any progress for this 👍

**Comment by shinyquagsire23** [comment]
Implemented now, closing
