### ISSUE TITLE
Mouse Sensitivity Sliders go backward slightly when swapping between Horizontal and Vertical Settings

### ISSUE THREAD

**Issue by Journeyman716** [shinyquagsire23/OpenJKDF2#62]
As the title says, when switching between the Horizontal and Vertical Look settings in the Mouse menu, the sliders seem to be set slightly lower than they were when last clicked on, eg. Horizontal sensitivity is 50, and Vertical is 45, but Horizontal is currently selected, swapping to vertical makes the value 44, and switching to Horizontal sets it's value from 50 to 49, and this can be done until both are at 0.

**Comment by shinyquagsire23** [comment]
Fixed v0.3.1
