### ISSUE TITLE
JKM/ Mysteries of the Sith container support

### ISSUE THREAD

**Issue by Alex3474247** [shinyquagsire23/OpenJKDF2#63]
As the title says, it would be great if OpenJKDF2 would support .goo container format and MotS game. And I think JKM.EXE engine is slightly modified JK.EXE, there is the level in the game, Dark Swamp and Temple Catacombs, where no weapons are working except lightsaber.

**Comment by shinyquagsire23** [comment]
MoTS is definitely planned, but my understanding is that it adds enough to the engine that it would likely be its own project. Or at the very least, I would need to figure out an exact catalogue of everything actually added to MoTS so I can patch it into OpenJKDF2 instead of re-reversing MoTS.

**Comment by Alex3474247** [comment]
If I was doing a reversing, I would unpack and dig into game resources, first of all, scripts, and check out, if there are any new functions calls here. And of course, I'll read this article https://en.wikipedia.org/wiki/Star_Wars_Jedi_Knight:_Mysteries_of_the_Sith

**Comment by StrikerMan780** [comment]
As far as I know, the major things that MoTS added were colored lighting, and a different video format? (Probably some COG stuff too)

**Comment by Alex3474247** [comment]
Yes, there is an article at Wikipedia about it https://en.wikipedia.org/wiki/Star_Wars_Jedi_Knight:_Mysteries_of_the_Sith

**Comment by TRPB** [comment]
It's also worth checking the unofficial JK specs: https://www.massassi.net/jkspecs/index.htm which has at least a starting point of cog verbs (listed here: https://www.massassi.net/jkspecs/cog_mots.htm there's quite a few) and additions to jkl files (which looks like just lighting)

**Comment by shinyquagsire23** [comment]
Yeah, the lighting I'd actually wanted to backport to JKDF2 for the sake of like, shaders and whatnot idk. The thing I'm worried about though is stuff like bug fixes where particularities can be extremely subtle, COG verbs are actually the easier thing to add.

**Comment by StrikerMan780** [comment]
Having the MOTS coloured lighting in DF2 honestly would be amazing. Especially if it would be possible to add it to the existing maps (Similar to .lit files for Quake).

**Comment by shinyquagsire23** [comment]
`.goo` loading is implemented in v0.6.9 with the `-motsCompat` cmdline flag, further MoTS bugs should get their own issues though so I'll close this
