### ISSUE TITLE
[0.3.9] Only some surfaces seem to be affected by bloom? (EDIT: Emissive lights subtracted by dynamic)

### ISSUE THREAD

**Issue by StrikerMan780** [shinyquagsire23/OpenJKDF2#69]
For some odd reason, the top of this passageway is affected by bloom, but the other surfaces are not?

![image](https://shadowmavericks.com/files/ShareX/openjkdf2-64_2022-01-11_22-31-51.png)

**Comment by StrikerMan780** [comment]
Hmm, the lighting here seems to be behaving oddly to begin with. (Even with bloom off), not sure what's up, but it seems any time a dynamic light is nearby, it subtracts from the brightness?

![video](https://shadowmavericks.com/files/ShareX/2022-01-13_18-33-20.mp4)

**Comment by shinyquagsire23** [comment]
Ended up fixing this in one release for other reasons, forget which though
