### ISSUE TITLE
Use a default FPS limit to save power and prevent audible GPU coil whine

### ISSUE THREAD

**Issue by Calinou** [shinyquagsire23/OpenJKDF2#70]
When I started the game for the first time, I could hear coil whine from my GPU (and in my headphones) during the opening cinematic. This is because the default framerate is uncapped, and modern GPUs often produce coil whine when rendering at very high framerates.

Using a high FPS cap (ideally one that matches the monitor refresh rate) should alleviate this a lot, while reducing power consumption (and heat emissions).
SDL has an API to get the monitor refresh rate, but even if this doesn't work, capping to 145 FPS by default should still alleviate most of the audible coil whine. (145 FPS allows supporting 144 Hz monitor users out of the box without resulting in tearing when V-Sync is disabled, which is why I consider it to be a sweet spot nowadays.)

Also, it may make sense to temporarily limit FPS to a low value during cutscenes to further save power (regardless of the current FPS limit). Limiting to 60 FPS or even 30 FPS in those cases should be fine.

**Edit:** It seems the in-game FPS limit isn't applied at all to cutscenes and menus currently, which would explain why I can hear coil whine even when a relatively low FPS limit is set.

**Comment by shinyquagsire23** [comment]
Yeah the menu drawing is honestly kind of a mess, I can't remember if I set it to always vsync in the menus or if I had it uncapped. I definitely uncap it during loading though, because otherwise the draw calls for the loading bar will make loading like 2x as slow. I think I could probably set a 60fps cutscene limiter though.

**Comment by shinyquagsire23** [comment]
Fixed v0.5.3
