### ISSUE TITLE
F11 quick load causes a crash to desktop

### ISSUE THREAD

**Issue by Khan-D-Man** [shinyquagsire23/OpenJKDF2#74]
When pressing F11 to load a quick save game, it will crash the Window and the game.  I tried this in windowed mode as well so to see the console and if anything was shown on the console before the crash completes, but nothing is displayed.  You get a slight sound pop as the audio starts to cut out and then the game just closes.

**Comment by shinyquagsire23** [comment]
OK turns out JK doesn't have a quick load function, F11 was just the screenshot function. Stubbed it out though so it at least won't crash, along with the gamma adjust key F10.

Fixed v0.3.12
