### ISSUE TITLE
save game overwrite crash

### ISSUE THREAD

**Issue by asmolcic** [shinyquagsire23/OpenJKDF2#75]
If you choose a previous save you don't get a confirmation dialog but the game crashes with:
`malloc(): memory corruption
Aborted`

Quicksave works fine.

OS build: Ubuntu 18
build: x64 (I cloned the repo on 2022-04-02)
game: GOG

Let me know if you need anything else.

**Comment by shinyquagsire23** [comment]
Should be fixed with the Flatpak fixes, if not let me know
