### ISSUE TITLE
XBOX 360 controler crashes the game when enabled in menu.

### ISSUE THREAD

**Issue by PatrykIBM** [shinyquagsire23/OpenJKDF2#81]
When attempting to enable controller in the menu and x360 controller is plugged in game freeze and crash.

**Comment by PatrykIBM** [comment]
From curiousity I checked generic "USB Gampead" as well and behavior is the same, freeze while cliking on Joistick option in Controls menu. No error output generated in the logbox.

Error occurred on Saturday, June 18, 2022 at 09:09:31.

openjkdf2-64.exe caused an Access Violation at location 000000000041BF00 DEP violation at location 000000000041BF00.

AddrPC           Params
000000000041BF00 00007FF66E2FB300 00007FF66E2FB200 000000010000006B
00007FF66E268332 00007FF66E2F5CE0 00007FF66E2F59E0 00000257EB1AC4E0  openjkdf2-64.exe!jkGuiSetup_Show
00007FF66E25DA2A 00007FF600000000 00000257F25BFCC0 00007FFF6DF38F20  openjkdf2-64.exe!jkGuiMain_Show
00007FF66E27A158 0000000000000003 0000025700000002 0000000000000000  openjkdf2-64.exe!jkMain_MainShow
00007FF66E279449 0000000000000000 000002570000000F 0000000000000000  openjkdf2-64.exe!jkMain_GuiAdvance
00007FF66E2938B0 0000000000000000 000000820000000F 0000000000000000  openjkdf2-64.exe!Window_Main_Loop
00007FF66E293AF9 0000025700000001 00000257EB1B9EB0 00000257EB2C0030  openjkdf2-64.exe!Window_Main_Linux
00007FF66E2B7312 0000000000000001 00000257EB1B9EB0 000000000000004D  openjkdf2-64.exe!SDL_main
00007FF66E2D0521 0000000000000000 000000000000004E 00007FF66E66BC88  openjkdf2-64.exe!main_getcmdline  [/Users/valve/release/SDL/SDL2-2.0.16-source/foo-x64/../src/main/windows/SDL_windows_main.c @ 82]
00007FF66E1E13C1 0000000000000000 0000000000000000 0000000000000000  openjkdf2-64.exe!__tmainCRTStartup
00007FF66E1E14D6 0000000000000000 0000000000000000 0000000000000000  openjkdf2-64.exe!WinMainCRTStartup
00007FFFA72E7034 0000000000000000 0000000000000000 0000000000000000  KERNEL32.DLL!BaseThreadInitThunk
00007FFFA7D22651 0000000000000000 0000000000000000 0000000000000000  ntdll.dll!RtlUserThreadStart



Xbox controller from thread start:

Error occurred on Saturday, April 16, 2022 at 11:45:48.

openjkdf2-64.exe caused an Access Violation at location 000000000041BF00 DEP violation at location 000000000041BF00.

AddrPC           Params
000000000041BF00 00007FF7F23EB300 00007FF7F23EB200 000000010000006B
00007FF7F2358332 00007FF7F23E5CE0 00007FF7F23E59E0 000001EDC676A820  openjkdf2-64.exe!jkGuiSetup_Show
00007FF7F234DA2A 00007FF700000000 000001EDCD323000 00007FFD830F8F20  openjkdf2-64.exe!jkGuiMain_Show
00007FF7F236A158 0000000000000003 000001ED00000002 0000000000000000  openjkdf2-64.exe!jkMain_MainShow
00007FF7F2369449 0000000000000000 000001ED0000000F 0000000000000000  openjkdf2-64.exe!jkMain_GuiAdvance
00007FF7F23838B0 0000000000000000 000000E20000000F 0000000000000000  openjkdf2-64.exe!Window_Main_Loop
00007FF7F2383AF9 000001ED00000001 000001EDC6779150 000001EDC66D0030  openjkdf2-64.exe!Window_Main_Linux
00007FF7F23A7312 0000000000000001 000001EDC6779150 000000000000004D  openjkdf2-64.exe!SDL_main
00007FF7F23C0521 0000000000000000 000000000000004E 00007FF7F275BC88  openjkdf2-64.exe!main_getcmdline  [/Users/valve/release/SDL/SDL2-2.0.16-source/foo-x64/../src/main/windows/SDL_windows_main.c @ 82]
00007FF7F22D13C1 0000000000000000 0000000000000000 0000000000000000  openjkdf2-64.exe!__tmainCRTStartup
00007FF7F22D14D6 0000000000000000 0000000000000000 0000000000000000  openjkdf2-64.exe!WinMainCRTStartup
00007FFDD3817034 0000000000000000 0000000000000000 0000000000000000  KERNEL32.DLL!BaseThreadInitThunk
00007FFDD4A62651 0000000000000000 0000000000000000 0000000000000000  ntdll.dll!RtlUserThreadStart

**Comment by shinyquagsire23** [comment]
Fixed v0.6.0
