### ISSUE TITLE
Cutscene menu crashes

### ISSUE THREAD

**Issue by DanKorell** [shinyquagsire23/OpenJKDF2#83]
Whenever I click on the Cutscenes button from the main menu, OpenJKDF2 crashes to desktop. As such  there is no way to rewatch unlocked cutscenes.

I'm using the v0.3.12 64-bit Debug Windows build.

**Comment by shinyquagsire23** [comment]
Oh yeah, I haven't decompiled that menu just yet so it's ~expected behavior. I should probably fix that because it's one of the last easy things to decompile before the multiplayer menus.

**Comment by shinyquagsire23** [comment]
Fixed v0.6.0
