### ISSUE TITLE
Display and Sound settings sometimes revert

### ISSUE THREAD

**Issue by DanKorell** [shinyquagsire23/OpenJKDF2#84]
I've noticed that sometimes the display and sound settings revert back to default. For instance, Windowed instead of fullscreen, all graphical effects like bloom and SSAO turned off, the music volume set back to maximum, etc.

In fact, I think the volume settings are reverting every time as each time I load OpenJKDF2, the music volume is back to the maximum and sound effects a little below max, so I keep having to switch these volumes around.

**Comment by shinyquagsire23** [comment]
Fixed v0.6.2
