### ISSUE TITLE
AMD Driver (22.7.1) Black Screen

### ISSUE THREAD

**Issue by armitom** [shinyquagsire23/OpenJKDF2#88]
The latest amd driver, which came with a massive re-write and improvements to opengl performance unfortunately seems to have broke something, the game starts, I can hear the click on the mouse in the menus but the window is black, its not crashing so no crash logs.

My specs: Win10 (21h2)/Ryzen 2600x/32gbram/RX-6600xt 8gb

I have attached a picture of the window/console log if that helps

To confirm I also took the time and when back to the previous AMD driver, and it worked fine.
![openjkdf2amdblk](https://user-images.githubusercontent.com/60841109/181772490-4a8abd6f-94a7-4ff1-b25c-fa86b0f2ccc3.png)

Worth a look if you guys find the time, and big thanks for everyone involved on the project!

**Comment by shinyquagsire23** [comment]
Ahh, ok I actually ran into this on Parallels + macOS, but I was kinda just hoping it was a Parallels bug. I'll see if I can fix it there and maybe it'll also fix AMD

**Comment by armitom** [comment]
> Ahh, ok I actually ran into this on Parallels + macOS, but I was kinda just hoping it was a Parallels bug. I'll see if I can fix it there and maybe it'll also fix AMD.
> 
> Just to clarify if it's the same issue, if you click through the menus blindly to get to New Game, does it display graphics afterwards?

Yes I can indeed confirm that after blindly making my way through the menus and go in-game the in-game graphics appeared!

**Comment by shinyquagsire23** [comment]
Should hopefully be fixed with v0.4.4

**Comment by armitom** [comment]
It works now, thank you for the quick fix!
