### ISSUE TITLE
Reverse engineering tip

### ISSUE THREAD

**Issue by smlu** [shinyquagsire23/OpenJKDF2#9]
Sorry to spam the issue list just for this suggestion but since game Indiana Jones and the Infernal Machine is based on the Sith engine take a look a it.
Hint: the Jones engine is compiled in debug mode 😉

**Comment by smlu** [comment]
To make myself more clear of what do I mean here's screenshot of pseudo-code of [sithActor_Remove](https://github.com/shinyquagsire23/OpenJKDF2/blob/408b5f5e3c2580274cf1d4ba343f4f57910c965c/df2_reimpl/src/World/sithActor.c#L191-L200) function in Jones engine:
![slika](https://user-images.githubusercontent.com/4377556/141343860-0211ed2b-74f5-4019-b671-4acfc47b28ce.png)

Since the binary is compiled in debug mode it contains lot's of debugging information and assert statements with error descriptions and file names. This could potentially be helpful also for reverse engineering JKDF2.
![slika](https://user-images.githubusercontent.com/4377556/141350985-4e74a14d-ab70-4b19-9cd9-dc89c3d8a035.png)

**Comment by shinyquagsire23** [comment]
...ohhhhhhh geez that's right in the files I was hoping to find more info about, thanks for the tip!

**Comment by smlu** [comment]
Note that Jones engine is modified version of Sith engine although it uses many components from the original engine.
Mose notable is the lighting system which was rewritten (e.g. sector can have point light which illuminates game objects), it uses DirectX 6, RGB colors, 16 BPP textures etc ... And of course there are many different COG vm functions.

If you want I can contact you and share some more info.
