### ISSUE TITLE
Indiana Jones and infernal machine

### ISSUE THREAD

**Issue by paolo-caroni** [shinyquagsire23/OpenJKDF2#90]
Since the sith engine was used for df2, grim fandango and Indiana Jones the infernal machine (with improvements and modifications) there are plans to support this games too?

**Comment by shinyquagsire23** [comment]
Not particularly? MoTS is definitely next on my personal roadmap, and I've looked at Indy because it has a lot of debug strings which gave me canonical file names. So if someone did want to RE Indy, most of the code would probably be easily transferable.
