### ISSUE TITLE
mouse turning bug

### ISSUE THREAD

**Issue by 000MDK** [shinyquagsire23/OpenJKDF2#91]
can turn left indefinitely with mouse but not right: when turning right, the mouse cursor appears on the right screen edge and turning in-game stops. game not losing focus. Happens in fullscreen and windowed mode.

AMD GPU, Windows 11 (latest release drivers/os-build), OpenJKDF2 v0.5.2 DEBUG x64

**Comment by shinyquagsire23** [comment]
Fixed v0.5.3
