### ISSUE TITLE
[Issue/Suggestion] Surround sound 

### ISSUE THREAD

**Issue by KainXVIII** [shinyquagsire23/OpenJKDF2#93]
Original game had nice sound positioning through A3D, you can even emulate it if you had Sound Blaster X-fi cards even on Windows 10, is it possible to implement something similar?
Surround sound in OpenJKDF2 right now is pretty buggy - most of the SFX (menu sounds, voices, sounds of gunshots) are playing only from rear speakers..
PS - if i set my speakers from 5.1 to stereo game also does not sound right, I can't put into words how though..Like it too narrow, almost mono sound..

**Comment by shinyquagsire23** [comment]
Yeah this is actually something I want to look into, because the game ~does actually have a lot of code for keeping track of sound positions. The sound subsystem is just also one of the areas with the most unknown flags so I was hesitant to try getting proper binaural/surround added before I document it better and clean up the code.

**Comment by KainXVIII** [comment]
> Yeah this is actually something I want to look into, because the game ~does actually have a lot of code for keeping track of sound positions. The sound subsystem is just also one of the areas with the most unknown flags so I was hesitant to try getting proper binaural/surround added before I document it better and clean up the code.

Great to hear!

**Comment by 000MDK** [comment]
FYI/workaround, I replaced the OPENAL32.dll with latest openal-soft as soft_oal.dll and EFX as OPENAL32.dll, with presets/hrtf_defs setup in alsoft.ini for 5.1 output: sound only comes out of my front speakers

**Comment by shinyquagsire23** [comment]
Possibly implemented in v0.6.3? There might be some bugs to iron out though.

**Comment by KainXVIII** [comment]
> Implemented in v0.6.3? There might be some bugs to iron out though.

Sounds much better now, need more testing though!

**Comment by 000MDK** [comment]
Now, I have sound from my back speakers too, very nice! :D (Still using a different opengl32.dll BTW) @shinyquagsire23 FYI [gzdoom sourcecode](https://github.com/ZDoom/gzdoom/tree/master/src/sound) might be worth a look, they have good 3d audio working over there

**Comment by KainXVIII** [comment]
> sometimes I have to disable/re-enable A3D because it reverts to stereo - maybe savegame related?

yes, i have same issue (also same issue with number of sound channels, does it matter in this port anyway lol?)

**Comment by shinyquagsire23** [comment]
Hopefully fixed v0.6.8
